import { WikiLayout } from "@/components/WikiLayout";

export default function ThinCallerPage(): React.ReactElement {
  return (
    <WikiLayout title="Thin Caller & Reusable Workflow" description="How a service repo invokes the ops repo's deploy workflow.">
      <div className="prose-wiki max-w-3xl">
        <h1>Thin Caller &amp; Reusable Workflow</h1>
        <p>
          A service repo does not contain deploy logic. It contains a <strong>thin caller</strong>{" "}
          — a small GitHub Actions workflow that invokes the reusable{" "}
          <code>workflow_call</code> in the ops repo. All the real work happens in the reusable
          workflow and the <a href="/docs/deploy/orchestrator">orchestrator</a>. You don{"'"}t write
          the caller by hand —{" "}
          <a href="/docs/cli/generate"><code>foundry generate callers</code></a> emits it from the
          central <a href="/docs/manifest/central"><code>platform.json</code></a>.
        </p>

        <h2>The reusable workflow</h2>
        <p>
          The ops repo{"'"}s <code>.github/workflows/deploy.yml</code> is a reusable workflow. Its
          inputs:
        </p>
        <table>
          <thead>
            <tr><th>Input</th><th>Required</th><th>Default</th><th>Description</th></tr>
          </thead>
          <tbody>
            <tr><td><code>service</code></td><td>yes</td><td>—</td><td>Service key in <code>platform.json</code> (e.g. <code>web</code>)</td></tr>
            <tr><td><code>environment</code></td><td>no</td><td><code>prod</code></td><td>Environment to deploy (maps to a branch in the manifest)</td></tr>
          </tbody>
        </table>

        <h2>What it does</h2>
        <ol>
          <li>Checks out the caller repo.</li>
          <li>Mints a short-lived GitHub App token scoped to read the ops repo.</li>
          <li>Checks out the ops repo (manifest + orchestrator).</li>
          <li>Reads <code>platform.json</code> to resolve the service{"'"}s AWS <code>roleArn</code> and <code>region</code>.</li>
          <li>Sets up Node + corepack + OpenTofu.</li>
          <li>Configures AWS credentials via OIDC (assumes the resolved role — no long-lived keys).</li>
          <li>Runs the orchestrator against the checked-out caller repo.</li>
        </ol>

        <h2>The generated caller</h2>
        <p>
          For a service <code>web</code> at path <code>app</code> on branch <code>main</code>,{" "}
          <code>foundry generate callers</code> writes{" "}
          <code>.github/workflows/deploy.yml</code>:
        </p>
        <pre><code>{`name: "Deploy: web"

# Thin caller - generated by \`foundry generate callers\` from the central
# platform.json. The ops repo owns the pipeline; this repo names the service.

on:
  push:
    branches: [main]
    paths: ['app/**', '.github/workflows/deploy.yml']
  workflow_dispatch:

concurrency:
  group: foundry-deploy-web-\${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: your-org/your-ops-repo/.github/workflows/deploy.yml@main
    with:
      service: web
      environment: prod
    secrets: inherit`}</code></pre>
        <ul>
          <li><strong>Trigger</strong> — <code>push</code> to the service{"'"}s branch (from its <a href="/docs/manifest/environments">environments</a> override), path-scoped to its subdir when it has one, plus <code>workflow_dispatch</code>.</li>
          <li><strong>uses</strong> — the reusable ref is derived from the manifest (<code>&lt;org&gt;/&lt;ops-repo&gt;/.github/workflows/deploy.yml@&lt;ref&gt;</code>), not hard-coded to one org.</li>
          <li><strong>secrets: inherit</strong> — forwards the org-level secrets (the GitHub App credentials) the reusable workflow needs.</li>
          <li><strong>File name</strong> — <code>deploy.yml</code> for a repo{"'"}s only orchestrated service, or <code>deploy-&lt;service&gt;.yml</code> when a repo has several.</li>
        </ul>
        <p>No deploy steps, no AWS wiring, no strategy logic live in the service repo.</p>
      </div>
    </WikiLayout>
  );
}
