"""Thin-caller generator (multi-repo, v0.7.0).

From the central platform manifest, emit the per-service **thin-caller** GitHub
Actions workflow each service repo carries: it just names the service and
delegates to the foundry-ops reusable ``deploy.yml``. foundry-ops owns the
pipeline; repos stay thin. These are what `foundry generate` produces (and the
sync GitHub App delivers to the service repos).

Pure data → string. No I/O here; the command layer writes the files.
"""

from __future__ import annotations

from foundry_cli.core.project.manifest import ProjectManifest, ServiceConfig

# Strategies the orchestrated reusable deploy.yml handles on push. desktop /
# game-publisher ship via their own release flows (tag-release → *-release.yml);
# none / library are not deployed.
ORCHESTRATED_STRATEGIES = {"static", "service"}

# A literal GitHub Actions expression — kept out of f-strings to avoid brace
# escaping.
_GH_REF = "${{ github.ref }}"
_OPS_REUSABLE = "FoundryMedia/foundry-ops/.github/workflows/deploy.yml"


def generate_thin_caller(
    name: str,
    service: ServiceConfig,
    branch: str,
    env: str,
    filename: str,
    *,
    ref: str = "main",
) -> str:
    """Render one service's thin-caller workflow YAML."""
    lines: list[str] = [
        f'name: "Deploy: {name}"',
        "",
        "# Thin caller - generated by `foundry generate callers` from the central",
        "# platform.json. foundry-ops owns the pipeline; this repo names the service.",
        "",
        "on:",
        "  push:",
        f"    branches: [{branch}]",
    ]
    path = service.effective_path
    if path and path != ".":
        lines.append(f"    paths: ['{path}/**', '.github/workflows/{filename}']")
    lines += [
        "  workflow_dispatch:",
        "",
        "concurrency:",
        f"  group: foundry-deploy-{name}-{_GH_REF}",
        "  cancel-in-progress: false",
        "",
        "permissions:",
        "  id-token: write",
        "  contents: read",
        "",
        "jobs:",
        "  deploy:",
        f"    uses: {_OPS_REUSABLE}@{ref}",
        "    with:",
        f"      service: {name}",
        f"      environment: {env}",
        "    secrets: inherit",
    ]
    return "\n".join(lines) + "\n"


def generate_all_callers(
    manifest: ProjectManifest,
    env: str = "prod",
    *,
    ref: str = "main",
) -> dict[tuple[str, str], str]:
    """Map ``(repo, filename) -> workflow YAML`` for every orchestrated service.

    Services without their own ``repository`` fall back to the manifest's repo.
    Repos with more than one orchestrated service get ``deploy-<service>.yml``;
    a lone service gets the canonical ``deploy.yml``.
    """
    by_repo: dict[str, list[tuple[str, ServiceConfig]]] = {}
    for name, svc in manifest.services_config.items():
        if (svc.effective_strategy or "") not in ORCHESTRATED_STRATEGIES:
            continue
        repo = svc.repository or manifest.repository or "."
        by_repo.setdefault(repo, []).append((name, svc))

    out: dict[tuple[str, str], str] = {}
    for repo, svcs in by_repo.items():
        multi = len(svcs) > 1
        for name, svc in svcs:
            filename = f"deploy-{name}.yml" if multi else "deploy.yml"
            envs = manifest.resolve_environments(name)
            branch = envs[env].branch if env in envs else "main"
            out[(repo, filename)] = generate_thin_caller(
                name, svc, branch, env, filename, ref=ref
            )
    return out
