"""Thin-caller generator (multi-repo, v0.7.0).

From the central platform manifest, emit the per-service **thin-caller** GitHub
Actions workflow each service repo carries: it just names the service and
delegates to the platform ops repo's reusable ``deploy.yml``. The ops repo owns
the pipeline; service repos stay thin.

ORG-AGNOSTIC: nothing here is hard-coded to a particular company. The reusable
workflow reference (``<org>/<ops-repo>/.github/workflows/deploy.yml``) is derived
from the manifest — ``<org>`` from ``github.organization`` (or
``ecosystem.organization``) and ``<ops-repo>`` from the manifest's own
``repository`` (the repo the central manifest lives in). Another org points its
own manifest at its own ops repo and App; the SDK assumes nothing about ours.

Pure data → string. No I/O here; the command layer writes the files.
"""

from __future__ import annotations

from foundry_cli.core.project.manifest import ProjectManifest, ServiceConfig

# Strategies the orchestrated reusable deploy.yml handles on push. desktop /
# game-publisher ship via their own release flows; none / library aren't deployed.
ORCHESTRATED_STRATEGIES = {"static", "service"}

# Convention: the ops repo exposes its reusable deploy pipeline at this path.
_OPS_WORKFLOW = ".github/workflows/deploy.yml"

# A literal GitHub Actions expression — kept out of f-strings to avoid brace
# escaping.
_GH_REF = "${{ github.ref }}"


def _manifest_org(manifest: ProjectManifest) -> str | None:
    """Owning GitHub org — from ``github.organization`` (v0.4.0+) or the
    deprecated ``ecosystem.organization``."""
    gh = manifest.data.get("github") or {}
    if isinstance(gh, dict) and gh.get("organization"):
        return gh["organization"]
    eco = manifest.data.get("ecosystem") or {}
    if isinstance(eco, dict) and eco.get("organization"):
        return eco["organization"]
    return None


def ops_reusable_ref(manifest: ProjectManifest, ref: str = "main") -> str:
    """``<org>/<ops-repo>/.github/workflows/deploy.yml@<ref>`` derived from the
    manifest. The ops repo is the repo the central manifest lives in
    (``manifest.repository``)."""
    org = _manifest_org(manifest)
    ops_repo = manifest.repository
    if not org or not ops_repo:
        raise ValueError(
            "Cannot derive the ops reusable workflow ref: the manifest must set "
            "github.organization (or ecosystem.organization) and repository."
        )
    return f"{org}/{ops_repo}/{_OPS_WORKFLOW}@{ref}"


def generate_thin_caller(
    name: str,
    service: ServiceConfig,
    branch: str,
    env: str,
    filename: str,
    ops_ref: str,
) -> str:
    """Render one service's thin-caller workflow YAML."""
    lines: list[str] = [
        f'name: "Deploy: {name}"',
        "",
        "# Thin caller - generated by `foundry generate callers` from the central",
        "# platform.json. The ops repo owns the pipeline; this repo names the service.",
        "",
        "on:",
        "  push:",
        f"    branches: [{branch}]",
    ]
    path = service.effective_path
    if path and path != ".":
        lines.append(f"    paths: ['{path}/**', '.github/workflows/{filename}']")
    lines += [
        "  workflow_dispatch:",
        "",
        "concurrency:",
        f"  group: foundry-deploy-{name}-{_GH_REF}",
        "  cancel-in-progress: false",
        "",
        "permissions:",
        "  id-token: write",
        "  contents: read",
        "",
        "jobs:",
        "  deploy:",
        f"    uses: {ops_ref}",
        "    with:",
        f"      service: {name}",
        f"      environment: {env}",
        "    secrets: inherit",
    ]
    return "\n".join(lines) + "\n"


def generate_all_callers(
    manifest: ProjectManifest,
    env: str = "prod",
    *,
    ref: str = "main",
) -> dict[tuple[str, str], str]:
    """Map ``(repo, filename) -> workflow YAML`` for every orchestrated service.

    Services without their own ``repository`` fall back to the manifest's repo.
    Repos with more than one orchestrated service get ``deploy-<service>.yml``;
    a lone service gets the canonical ``deploy.yml``.
    """
    ops_ref = ops_reusable_ref(manifest, ref)

    by_repo: dict[str, list[tuple[str, ServiceConfig]]] = {}
    for name, svc in manifest.services_config.items():
        if (svc.effective_strategy or "") not in ORCHESTRATED_STRATEGIES:
            continue
        repo = svc.repository or manifest.repository or "."
        by_repo.setdefault(repo, []).append((name, svc))

    out: dict[tuple[str, str], str] = {}
    for repo, svcs in by_repo.items():
        multi = len(svcs) > 1
        for name, svc in svcs:
            filename = f"deploy-{name}.yml" if multi else "deploy.yml"
            envs = manifest.resolve_environments(name)
            branch = envs[env].branch if env in envs else "main"
            out[(repo, filename)] = generate_thin_caller(
                name, svc, branch, env, filename, ops_ref
            )
    return out
