"""Pipeline generator — produces CI/CD workflow YAML from the manifest.

Reads ``foundry.json``, resolves deployment profiles via the convention
engine, and emits a GitHub Actions workflow file with:

- A ``detect-changes`` job (runs the change detector script)
- A ``deploy-iac`` job (runs IaC plan/apply)
- A ``migrate-databases`` job (runs Liquibase for each database)
- One ``deploy-{service}`` job per deployable service

The generated YAML is thin — it delegates all logic to ``ci/scripts/deploy.py``.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from foundry_cli.core.project.manifest import (
    EnvironmentConfig,
    ProjectManifest,
    StructureConfig,
)
from foundry_cli.generators.conventions import (
    DeploymentProfile,
    resolve_all_profiles,
)

_GENERATED_HEADER = """\
# ════════════════════════════════════════════════════════════════════════════
# GENERATED BY: foundry generate pipeline
# Manual edits may break regeneration — edit with intention.
# Regenerate with: foundry generate pipeline
# Source: foundry.json (schemaVersion {schema_version})
# ════════════════════════════════════════════════════════════════════════════
"""

_CUSTOM_MARKER = "# ── Custom Jobs (preserved across regeneration) ──"


def generate_pipeline_yaml(manifest: ProjectManifest) -> str:
    """Generate a complete GitHub Actions workflow YAML from a manifest.

    Args:
        manifest: A loaded ``ProjectManifest``.

    Returns:
        The full YAML content as a string.
    """
    data = manifest.data
    profiles = resolve_all_profiles(data)
    environments = manifest.environments
    structure = manifest.structure
    ci = data.get("ci", {})
    github = data.get("github", {})
    api_lib = github.get("apiLib", {})
    iac_tool = ci.get("iac", "opentofu")
    iac_dir = ci.get("iacDir", "ci/iac")
    schema_version = data.get("schemaVersion", "0.3.0")

    # Filter to deployable services only
    deployable = {
        name: profile
        for name, profile in sorted(profiles.items())
        if profile.is_deployable
    }

    # Collect databases that need migration
    databases = manifest.databases
    services_with_db = {
        name: profile
        for name, profile in deployable.items()
        if profile.database and profile.database in databases
    }

    # Build trigger branches (only from enabled environments)
    trigger_branches = sorted({
        env.branch for env in environments.values() if env.enabled
    })

    lines: list[str] = []

    # Header
    lines.append(_GENERATED_HEADER.format(schema_version=schema_version))

    # Workflow name and triggers
    lines.append(f"name: CI/CD Pipeline")
    lines.append("")
    lines.append("on:")
    lines.append("  push:")
    lines.append(f"    branches: [{', '.join(trigger_branches)}]")
    lines.append("  workflow_dispatch:")
    lines.append("    inputs:")
    lines.append("      force_services:")
    lines.append("        description: 'Comma-separated service names to force deploy'")
    lines.append("        required: false")
    lines.append("        type: string")
    lines.append("")

    # Concurrency — cancel in-progress runs when a new deploy starts
    lines.append("concurrency:")
    lines.append("  group: deploy-${{ github.ref }}")
    lines.append("  cancel-in-progress: true")
    lines.append("")

    # Permissions
    lines.append("permissions:")
    lines.append("  id-token: write")
    lines.append("  contents: read")
    lines.append("  packages: read")
    lines.append("")

    # Environment — opt into Node.js 24 for all actions
    lines.append("env:")
    lines.append("  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true")
    lines.append("")

    # ── detect-changes job ──
    lines.append("jobs:")
    lines.append("  detect-changes:")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("    outputs:")
    lines.append("      services: ${{ steps.detect.outputs.services }}")
    lines.append("      environment: ${{ steps.detect.outputs.environment }}")
    lines.append("      has_db_changes: ${{ steps.detect.outputs.has_db_changes }}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v5")
    lines.append("        with:")
    lines.append("          fetch-depth: 0")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with:")
    lines.append("          python-version: '3.11'")
    lines.append("      - run: pip install -r ci/scripts/requirements.txt")
    lines.append("      - id: detect")
    lines.append("        run: |")
    lines.append("          python3 ci/scripts/deploy.py detect \\")
    lines.append('            --git-before "${{ github.event.before }}" \\')
    lines.append('            --git-after "${{ github.sha }}" \\')
    lines.append('            --branch "${{ github.ref_name }}" \\')
    lines.append("            --force \"${{ github.event.inputs.force_services || '' }}\"")
    lines.append("")

    # ── deploy-iac job ──
    lines.append("  deploy-iac:")
    lines.append("    needs: detect-changes")
    lines.append("    if: needs.detect-changes.outputs.services != '[]'")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("    environment: ${{ needs.detect-changes.outputs.environment }}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v5")
    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with: { python-version: '3.11' }")
    _append_iac_setup(lines, iac_tool)
    lines.append("      - uses: aws-actions/configure-aws-credentials@v5")
    lines.append("        with:")
    lines.append("          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActionsRole")
    lines.append("          role-session-name: deploy-iac-${{ github.run_id }}")
    lines.append("          aws-region: ${{ vars.AWS_REGION }}")
    lines.append("      - run: pip install -r ci/scripts/requirements.txt")
    # Repackage any Lambda functions whose source files changed since the zip was built
    lines.append("      - name: Repackage Lambda functions")
    lines.append(f"        run: python3 ci/scripts/deploy.py repackage-lambdas --iac-dir {iac_dir}")
    lines.append("      - run: |")
    lines.append('          python3 ci/scripts/deploy.py iac \\')
    lines.append('            --environment "${{ needs.detect-changes.outputs.environment }}" \\')
    lines.append('            --operation plan-apply')
    lines.append("      - uses: actions/upload-artifact@v4")
    lines.append("        with:")
    lines.append("          name: iac-outputs")
    lines.append("          path: iac-outputs/")
    lines.append("          retention-days: 1")
    lines.append("")

    # ── migrate-databases job (only if there are databases) ──
    if databases:
        lines.append("  migrate-databases:")
        lines.append("    needs: [detect-changes, deploy-iac]")
        lines.append("    if: needs.detect-changes.outputs.has_db_changes == 'true'")
        lines.append("    runs-on: ubuntu-latest")
        lines.append("    environment: ${{ needs.detect-changes.outputs.environment }}")
        lines.append("    steps:")
        lines.append("      - uses: actions/checkout@v5")
        lines.append("      - uses: actions/download-artifact@v4")
        lines.append("        with: { name: iac-outputs, path: iac-outputs/ }")
        lines.append("      - uses: actions/setup-python@v5")
        lines.append("        with: { python-version: '3.11' }")
        lines.append("      - uses: aws-actions/configure-aws-credentials@v5")
        lines.append("        with:")
        lines.append("          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActionsRole")
        lines.append("          role-session-name: migrate-databases-${{ github.run_id }}")
        lines.append("          aws-region: ${{ vars.AWS_REGION }}")
        lines.append("      - run: pip install -r ci/scripts/requirements.txt")
        lines.append("      - run: |")
        lines.append('          python3 ci/scripts/deploy.py migrate \\')
        lines.append('            --environment "${{ needs.detect-changes.outputs.environment }}"')
        lines.append("")

    # ── Per-service deploy jobs ──
    lines.append(f"  # ── Service deploy jobs ({len(deployable)} services) ──")
    lines.append("")

    for svc_name, profile in deployable.items():
        _append_service_job(lines, svc_name, profile, databases, structure, api_lib)

    # ── Custom jobs marker ──
    lines.append(_CUSTOM_MARKER)
    lines.append("")

    return "\n".join(lines)


def _append_iac_setup(lines: list[str], iac_tool: str) -> None:
    """Append the IaC tool setup step."""
    if iac_tool == "opentofu":
        lines.append("      - uses: opentofu/setup-opentofu@v2")
        lines.append("        with: { tofu_version: '1.9.0' }")
    elif iac_tool == "terraform":
        lines.append("      - uses: hashicorp/setup-terraform@v3")
        lines.append("        with: { terraform_version: '1.9.0' }")


def _append_service_job(
    lines: list[str],
    name: str,
    profile: DeploymentProfile,
    databases: dict[str, Any],
    structure: StructureConfig,
    api_lib: dict[str, Any],
) -> None:
    """Append a per-service deploy job."""
    # Build the needs list
    needs = ["detect-changes", "deploy-iac"]
    if profile.database and profile.database in databases:
        needs.append("migrate-databases")

    needs_str = ", ".join(needs)

    lines.append(f"  deploy-{name}:")
    lines.append(f"    needs: [{needs_str}]")
    lines.append(f"    if: contains(fromJSON(needs.detect-changes.outputs.services), '{name}')")
    lines.append("    runs-on: ubuntu-latest")
    lines.append("    environment: ${{ needs.detect-changes.outputs.environment }}")
    lines.append("    steps:")
    lines.append("      - uses: actions/checkout@v5")
    lines.append("      - uses: actions/download-artifact@v4")
    lines.append("        with: { name: iac-outputs, path: iac-outputs/ }")

    # Docker setup for ECS services
    if profile.needs_docker:
        lines.append("      - uses: docker/setup-buildx-action@v3")

    # Node.js setup for static sites (pnpm must be installed BEFORE setup-node
    # because setup-node auto-detects packageManager from package.json)
    if profile.needs_node and not profile.needs_docker:
        lines.append("      - uses: pnpm/action-setup@v4")
        lines.append("      - uses: actions/setup-node@v5")
        lines.append("        with: { node-version: '22', cache: 'pnpm' }")

    lines.append("      - uses: actions/setup-python@v5")
    lines.append("        with: { python-version: '3.11' }")
    lines.append("      - uses: aws-actions/configure-aws-credentials@v5")
    lines.append("        with:")
    lines.append(f"          role-to-assume: arn:aws:iam::${{{{ vars.AWS_ACCOUNT_ID }}}}:role/GithubActionsRole")
    lines.append(f"          role-session-name: deploy-{name}-${{{{ github.run_id }}}}")
    lines.append("          aws-region: ${{ vars.AWS_REGION }}")
    lines.append("      - run: pip install -r ci/scripts/requirements.txt")

    # For service-strategy services: build-push then deploy
    if profile.strategy == "service":
        lines.append("      - run: |")
        lines.append(f"          python3 ci/scripts/deploy.py service \\")
        lines.append(f'            --name {name} \\')
        lines.append('            --environment "${{ needs.detect-changes.outputs.environment }}" \\')
        lines.append("            --operation build-push")
        # Spring Boot services need a token for GitHub Packages auth
        # Use PACKAGES_READ_TOKEN if apiLib is configured (cross-repo), else github.token
        if profile.type == "spring-boot":
            packages_secret = api_lib.get("packagesSecret")
            if packages_secret:
                lines.append("        env:")
                lines.append(f"          GITHUB_TOKEN: ${{{{ secrets.{packages_secret} }}}}")
            else:
                lines.append("        env:")
                lines.append("          GITHUB_TOKEN: ${{ github.token }}")
        lines.append("      - run: |")
        lines.append(f"          python3 ci/scripts/deploy.py service \\")
        lines.append(f'            --name {name} \\')
        lines.append('            --environment "${{ needs.detect-changes.outputs.environment }}" \\')
        lines.append("            --operation deploy")
    elif profile.strategy == "static":
        lines.append("      - run: |")
        lines.append(f"          python3 ci/scripts/deploy.py service \\")
        lines.append(f'            --name {name} \\')
        lines.append('            --environment "${{ needs.detect-changes.outputs.environment }}" \\')
        lines.append("            --operation build-deploy")

    lines.append("")


def write_pipeline(
    manifest: ProjectManifest,
    output_path: Path | None = None,
    *,
    force: bool = False,
    clean: bool = False,
) -> Path:
    """Generate and write the pipeline YAML file.

    Args:
        manifest: A loaded ``ProjectManifest``.
        output_path: Explicit path for the pipeline file.  When ``None`` the
            path is derived from ``ci.pipeline`` in the manifest.
        force: If ``True``, overwrite without checking for custom content.
        clean: If ``True``, delete the existing file before writing.

    Returns:
        Path to the written file.
    """
    if output_path is None:
        ci = manifest.data.get("ci", {})
        pipeline_path_str = ci.get("pipeline", ".github/workflows/ci-cd-pipeline.yml")
        # Try manifest.path first, fall back to cwd
        if hasattr(manifest, "path") and manifest.path:
            output_path = manifest.path.parent / pipeline_path_str
        else:
            output_path = Path.cwd() / pipeline_path_str

    yaml_content = generate_pipeline_yaml(manifest)

    # Clean mode: wipe existing file
    if clean and output_path.exists():
        output_path.unlink()

    # Preserve custom jobs from existing file
    if output_path.exists() and not force and not clean:
        existing = output_path.read_text(encoding="utf-8")
        if _CUSTOM_MARKER in existing:
            custom_section = existing.split(_CUSTOM_MARKER, 1)[1]
            yaml_content = yaml_content.rsplit(_CUSTOM_MARKER, 1)[0] + _CUSTOM_MARKER + custom_section

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(yaml_content, encoding="utf-8")
    return output_path


__all__ = [
    "generate_pipeline_yaml",
    "write_pipeline",
]
