"""Scripts generator — produces the complete ``ci/scripts/`` directory from the manifest.

This module generates every Python file in ``ci/scripts/`` including:

- ``core/`` — manifest reader, convention engine, secrets handler
- ``engines/`` — ECS, S3 static, IaC, and database migration engines
- ``orchestration/`` — change detector, dependency graph, coordinator
- ``deploy.py`` — unified CLI entry point
- ``requirements.txt`` — pinned dependencies

All generated files are self-contained — they do NOT depend on the Foundry CLI
at runtime.  They read ``foundry.json`` directly and resolve deployment profiles
using an embedded copy of the convention engine.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from foundry_cli.core.project.manifest import ProjectManifest

# ── Header for all generated files ───────────────────────────────────────

_HEADER = '''\
# ════════════════════════════════════════════════════════════════════════════
# GENERATED BY: foundry generate scripts
# Manual edits may break regeneration — edit with intention.
# Regenerate with: foundry generate scripts --clean
# Source: foundry.json (schemaVersion {schema_version})
# ════════════════════════════════════════════════════════════════════════════
'''


def generate_scripts(manifest: ProjectManifest, output_dir: Path, *, clean: bool = False) -> list[Path]:
    """Generate the complete ``ci/scripts/`` directory tree.

    Args:
        manifest: A loaded ``ProjectManifest``.
        output_dir: Absolute path to the target ``ci/scripts/`` directory.
        clean: If ``True``, delete and recreate the directory from scratch.

    Returns:
        List of all generated file paths.
    """
    schema_version = manifest.data.get("schemaVersion", "0.3.0")
    header = _HEADER.format(schema_version=schema_version)

    if clean and output_dir.exists():
        shutil.rmtree(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []

    # Generate each module
    for rel_path, content_fn in _FILE_GENERATORS.items():
        file_path = output_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        content = content_fn(manifest, header)
        file_path.write_text(content, encoding="utf-8")
        generated.append(file_path)

    return generated


# ── File content generators ──────────────────────────────────────────────
# Each function takes (manifest, header) and returns the full file content.


def _gen_requirements(manifest: ProjectManifest, header: str) -> str:
    return f"""{header}
boto3>=1.34.0
click>=8.1.0
"""


def _gen_core_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Core modules for manifest-driven deployment."""\n'


def _gen_engines_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Deployment engines — one per deployment strategy."""\n'


def _gen_orchestration_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Orchestration — change detection, dependency ordering, coordination."""\n'


def _gen_manifest_reader(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Reads foundry.json and resolves deployment profiles.

This is a self-contained manifest reader — it does NOT depend on the
Foundry CLI.  It reads the raw JSON and delegates to the convention engine.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class SecretMapping:
    """Maps a Secrets Manager secret to a file in the build context."""
    source: str
    target: str
    format: str = "raw"
    extract_key: str | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SecretMapping":
        return cls(
            source=data["source"],
            target=data["target"],
            format=data.get("format", "raw"),
            extract_key=data.get("extractKey"),
        )


@dataclass(frozen=True)
class SidecarDeployConfig:
    """ECS sidecar container configuration."""
    image: str
    port: int | None = None
    cpu: int = 128
    memory: int = 256
    command: tuple[str, ...] = field(default_factory=tuple)
    environment: dict[str, str] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SidecarDeployConfig":
        return cls(
            image=data["image"],
            port=data.get("port"),
            cpu=data.get("cpu", 128),
            memory=data.get("memory", 256),
            command=tuple(data.get("command", [])),
            environment=dict(data.get("environment", {{}})),
        )


@dataclass(frozen=True)
class CdnConfig:
    """CDN configuration for static/frontend deployments."""
    distribution_id_output: str | None = None
    invalidation_paths: tuple[str, ...] = ("/*",)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CdnConfig":
        paths = data.get("invalidationPaths", ["/*"])
        return cls(
            distribution_id_output=data.get("distributionIdOutput"),
            invalidation_paths=tuple(paths) if isinstance(paths, list) else ("/*",),
        )


@dataclass(frozen=True)
class DeployConfig:
    """Deployment configuration overrides."""
    strategy: str | None = None
    dockerfile: str | None = None
    build_context: str | None = None
    build_command: str | None = None
    secrets: tuple[SecretMapping, ...] = field(default_factory=tuple)
    cdn: bool | CdnConfig | None = None
    depends_on: tuple[str, ...] = field(default_factory=tuple)
    sidecars: dict[str, SidecarDeployConfig] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeployConfig":
        raw_secrets = data.get("secrets", [])
        secrets = tuple(SecretMapping.from_dict(s) for s in raw_secrets if isinstance(s, dict))
        raw_cdn = data.get("cdn")
        cdn: bool | CdnConfig | None = None
        if isinstance(raw_cdn, bool):
            cdn = raw_cdn
        elif isinstance(raw_cdn, dict):
            cdn = CdnConfig.from_dict(raw_cdn)
        raw_sidecars = data.get("sidecars", {{}})
        sidecars = {{}}
        if isinstance(raw_sidecars, dict):
            for name, sc_data in raw_sidecars.items():
                if isinstance(sc_data, dict):
                    sidecars[name] = SidecarDeployConfig.from_dict(sc_data)
        return cls(
            strategy=data.get("strategy"),
            dockerfile=data.get("dockerfile"),
            build_context=data.get("buildContext"),
            build_command=data.get("buildCommand"),
            secrets=secrets,
            cdn=cdn,
            depends_on=tuple(data.get("dependsOn", [])),
            sidecars=sidecars,
        )


@dataclass(frozen=True)
class ServiceConfig:
    """Lean service definition from foundry.json.

    v0.5.0: ``scope``, ``stack`` (type/framework/language), ``deploy`` (strategy),
            ``run`` (port/args), ``database`` (inline).
    v0.4.0 compat: ``kind``→stack.type, ``type``→stack.framework, ``role``→scope.
    """
    kind: str | None = None          # stack.type (backend/frontend/package)
    type: str | None = None          # stack.framework (spring-boot, nextjs, etc.)
    role: str | None = None          # scope (public/internal)
    database: str | dict[str, Any] | None = None
    deploy: DeployConfig | None = None

    # --- helper properties ---------------------------------------------------

    @property
    def database_name(self) -> str | None:
        """Logical database name (service name when inline dict, string ref otherwise)."""
        if isinstance(self.database, dict):
            return None  # caller must use the service name as db_name
        return self.database

    @property
    def database_config(self) -> dict[str, Any] | None:
        """Database config dict when declared inline; ``None`` for string refs."""
        return self.database if isinstance(self.database, dict) else None

    @property
    def strategy(self) -> str | None:
        """Deployment strategy from the deploy block."""
        return self.deploy.strategy if self.deploy else None

    @property
    def effective_strategy(self) -> str | None:
        """Deploy block strategy (normalised: ecs→service, s3-static→static)."""
        raw = self.deploy.strategy if self.deploy else None
        if not raw:
            return None
        return {{"ecs": "service", "s3-static": "static"}}.get(raw, raw)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ServiceConfig":
        # ── Stack resolution ─────────────────────────────────────────
        stack = data.get("stack", {{}})
        if isinstance(stack, dict) and stack:
            stack_type = stack.get("type")
            stack_framework = stack.get("framework")
        else:
            stack_type = data.get("kind")
            stack_framework = data.get("type")

        # ── Scope → role ─────────────────────────────────────────────
        scope = data.get("scope") or data.get("role")

        # ── Deploy block ─────────────────────────────────────────────
        deploy = None
        if "deploy" in data and isinstance(data["deploy"], dict):
            deploy = DeployConfig.from_dict(data["deploy"])
        elif data.get("strategy"):
            # v0.4.0 flat strategy → synthesize a DeployConfig
            deploy = DeployConfig(strategy=data["strategy"])

        return cls(
            kind=stack_type,
            type=stack_framework,
            role=scope,
            database=data.get("database"),
            deploy=deploy,
        )


@dataclass(frozen=True)
class StructureConfig:
    """Directory layout from the structure block."""
    apps_dir: str = "apps"
    ci_dir: str = "ci"
    packages_dir: str = "packages"

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StructureConfig":
        return cls(
            apps_dir=data.get("appsDir", "apps"),
            ci_dir=data.get("ciDir", "ci"),
            packages_dir=data.get("packagesDir", "packages"),
        )


@dataclass(frozen=True)
class EnvironmentConfig:
    """Maps a deployment environment to a Git branch."""
    branch: str
    enabled: bool = True
    auto_approve: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EnvironmentConfig":
        return cls(
            branch=data["branch"],
            enabled=data.get("enabled", True),
            auto_approve=data.get("autoApprove", False),
        )


class Manifest:
    """Parsed foundry.json with convenience accessors."""

    def __init__(self, data: dict[str, Any]):
        self.data = data

    @classmethod
    def load(cls, path: Path | None = None) -> "Manifest":
        if path is None:
            path = Path("foundry.json")
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls(data)

    @property
    def name(self) -> str:
        return self.data.get("name", "")

    @property
    def prefix(self) -> str:
        # v0.4.0: top-level prefix
        if p := self.data.get("prefix"):
            return p
        # v0.3.0 fallback: ecosystem.prefix
        eco = self.data.get("ecosystem", {{}})
        if p := eco.get("prefix"):
            return p
        words = self.name.split()
        return "".join(w[0] for w in words if w and w[0].isalpha()).lower()

    @property
    def github(self) -> dict[str, Any]:
        """GitHub org/repo info (v0.4.0 ``github`` block, falls back to ``ecosystem``)."""
        return self.data.get("github") or self.data.get("ecosystem", {{}})

    @property
    def organization(self) -> str:
        return self.github.get("organization", "")

    @property
    def structure(self) -> StructureConfig:
        raw = self.data.get("structure", {{}})
        return StructureConfig.from_dict(raw) if isinstance(raw, dict) else StructureConfig()

    @property
    def services(self) -> dict[str, ServiceConfig]:
        raw = self.data.get("services", {{}})
        return {{name: ServiceConfig.from_dict(cfg) for name, cfg in raw.items() if isinstance(cfg, dict)}}

    @property
    def databases(self) -> dict[str, Any]:
        # v0.3.0: top-level databases block
        top = self.data.get("databases", {{}})
        if top:
            return top
        # v0.4.0: aggregate from per-service inline database dicts
        agg: dict[str, Any] = {{}}
        for svc_name, svc_raw in self.data.get("services", {{}}).items():
            if isinstance(svc_raw, dict) and isinstance(svc_raw.get("database"), dict):
                agg[svc_name] = svc_raw["database"]
        return agg

    @property
    def ci(self) -> dict[str, Any]:
        return self.data.get("ci", {{}})

    @property
    def environments(self) -> dict[str, EnvironmentConfig]:
        raw = self.ci.get("environments", {{}})
        if not raw:
            return {{
                "prod": EnvironmentConfig(branch="release"),
                "dev": EnvironmentConfig(branch="develop"),
                "test": EnvironmentConfig(branch="qa"),
            }}
        return {{name: EnvironmentConfig.from_dict(cfg) for name, cfg in raw.items() if isinstance(cfg, dict)}}

    def resolve_environment(self, branch: str) -> str | None:
        for env_name, env_cfg in self.environments.items():
            if env_cfg.branch == branch and env_cfg.enabled:
                return env_name
        return None
'''


def _gen_conventions(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Convention engine — resolves deployment profiles from service identity.

Pure functions, no I/O, no AWS calls.  Input is manifest data, output is
a fully-resolved DeploymentProfile.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from core.manifest_reader import (
    CdnConfig,
    DeployConfig,
    Manifest,
    SecretMapping,
    ServiceConfig,
    SidecarDeployConfig,
    StructureConfig,
)


@dataclass(frozen=True)
class DeploymentProfile:
    """Fully-resolved deployment configuration for a single service."""
    name: str
    kind: str
    type: str
    role: str
    strategy: str
    dockerfile: str | None
    build_context: str
    build_command: str | None
    secrets: tuple[SecretMapping, ...]
    cdn: bool | CdnConfig | None
    depends_on: tuple[str, ...]
    sidecars: dict[str, SidecarDeployConfig]
    watch_paths: tuple[str, ...]
    database: str | None

    @property
    def is_deployable(self) -> bool:
        return self.strategy != "none"

    @property
    def needs_docker(self) -> bool:
        return self.strategy == "service"

    @property
    def needs_node(self) -> bool:
        return self.type in ("nextjs", "vite", "react", "vue", "angular")

    @property
    def needs_database_migration(self) -> bool:
        return self.database is not None


STRATEGY_DEFAULTS: dict[tuple[str, str | None], str] = {{
    ("backend", "spring-boot"): "service",
    ("backend", "uvicorn"): "service",
    ("backend", "gunicorn"): "service",
    ("backend", "express"): "service",
    ("backend", "django"): "service",
    ("backend", "flask"): "service",
    ("backend", None): "service",
    ("frontend", "vite"): "static",
    ("frontend", "react"): "static",
    ("frontend", "vue"): "static",
    ("frontend", "angular"): "static",
    ("frontend", "nextjs"): "service",
    ("frontend", None): "service",
    ("package", None): "none",
}}

BUILD_CONTEXT_DEFAULTS: dict[tuple[str, str | None], str] = {{
    ("backend", "spring-boot"): ".",
    ("backend", "uvicorn"): "{{apps_dir}}/backend/{{name}}",
    ("backend", "gunicorn"): "{{apps_dir}}/backend/{{name}}",
    ("backend", "express"): ".",
    ("backend", None): "{{apps_dir}}/backend/{{name}}",
    ("frontend", "nextjs"): ".",
    ("frontend", None): "{{apps_dir}}/frontend/{{name}}",
}}


def resolve_profile(
    name: str,
    service: ServiceConfig,
    structure: StructureConfig,
    databases: dict[str, Any],
) -> DeploymentProfile:
    """Resolve a complete DeploymentProfile from service config + conventions."""
    kind = service.kind or "backend"
    type_ = service.type
    role = service.role or "other"
    deploy = service.deploy or DeployConfig()

    # Resolve database name — inline dict uses service name;
    # string reference to top-level databases block.
    if isinstance(service.database, dict):
        db = name  # Service name IS the logical DB name
    elif isinstance(service.database, str):
        db = service.database
    else:
        db = None

    # Strategy — deploy block > convention default
    _LEGACY = {{"ecs": "service", "s3-static": "static"}}
    raw = (
        (deploy.strategy if deploy else None)
        or STRATEGY_DEFAULTS.get(
            (kind, type_), STRATEGY_DEFAULTS.get((kind, None), "none")
        )
    )
    strategy = _LEGACY.get(raw, raw)

    dockerfile: str | None = None
    if strategy == "service":
        dockerfile = deploy.dockerfile or f"{{structure.apps_dir}}/{{kind}}/{{name}}/Dockerfile"

    ctx_template = BUILD_CONTEXT_DEFAULTS.get(
        (kind, type_), BUILD_CONTEXT_DEFAULTS.get((kind, None), f"{{structure.apps_dir}}/{{kind}}/{{name}}")
    )
    build_context = deploy.build_context or ctx_template.format(
        apps_dir=structure.apps_dir, kind=kind, name=name,
    )

    build_command: str | None = None
    if strategy == "static" and type_ in ("nextjs", "vite", "react", "vue", "angular"):
        build_command = deploy.build_command or "pnpm build"

    sidecars = dict(deploy.sidecars) if deploy.sidecars else {{}}

    if deploy.secrets:
        secrets = deploy.secrets
    else:
        secrets = _default_secrets(kind, type_, role, name, strategy, structure)

    if deploy.cdn is not None:
        cdn = deploy.cdn
    elif strategy == "static":
        cdn = True
    elif kind == "frontend" and strategy == "service":
        cdn = True
    else:
        cdn = False

    if deploy.depends_on:
        depends_on = deploy.depends_on
    else:
        deps: list[str] = ["iac"] if strategy != "none" else []
        if db and db in databases:
            deps.append(f"database:{{db}}")
        for sc_name in sidecars:
            deps.append(f"sidecar:{{sc_name}}")
        depends_on = tuple(deps)

    apps_dir = structure.apps_dir
    packages_dir = structure.packages_dir
    if kind == "backend":
        watch_paths = (f"^{{apps_dir}}/backend/{{name}}/",)
    elif kind == "frontend":
        watch_paths = (f"^{{apps_dir}}/frontend/{{name}}/", f"^{{packages_dir}}/")
    elif kind == "package":
        watch_paths = (f"^{{packages_dir}}/{{name}}/",)
    else:
        watch_paths = ()

    return DeploymentProfile(
        name=name, kind=kind, type=type_ or "other", role=role,
        strategy=strategy, dockerfile=dockerfile, build_context=build_context,
        build_command=build_command, secrets=secrets, cdn=cdn,
        depends_on=depends_on, sidecars=sidecars, watch_paths=watch_paths,
        database=db,
    )


def _default_secrets(
    kind: str, type_: str | None, role: str | None,
    name: str, strategy: str, structure: StructureConfig,
) -> tuple[SecretMapping, ...]:
    if strategy == "none":
        return ()
    apps_dir = structure.apps_dir
    secrets: list[SecretMapping] = []
    if type_ == "spring-boot":
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/microlith-spring-properties",
            target=f"{{apps_dir}}/backend/{{{{service}}}}/src/main/resources/application-{{{{env}}}}.yml",
        ))
        if role == "auth":
            secrets.append(SecretMapping(
                source="{{prefix}}-{{env}}/efga-spring-properties",
                target=f"{{apps_dir}}/backend/{{{{service}}}}/src/main/resources/efga-{{{{env}}}}.yml",
            ))
    elif type_ in ("uvicorn", "gunicorn", "flask", "django"):
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/{{service}}-env",
            target=f"{{apps_dir}}/backend/{{{{service}}}}/.env",
        ))
    elif kind == "frontend":
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/{{service}}-env",
            target=f"{{apps_dir}}/frontend/{{{{service}}}}/.env.production",
        ))
    return tuple(secrets)


def resolve_all_profiles(manifest: Manifest) -> dict[str, DeploymentProfile]:
    """Resolve deployment profiles for all services in a manifest."""
    structure = manifest.structure
    databases = manifest.databases
    profiles: dict[str, DeploymentProfile] = {{}}
    for name, svc in manifest.services.items():
        profiles[name] = resolve_profile(name, svc, structure, databases)
    return profiles
'''


def _gen_secrets(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Secret fetching — downloads secrets from Secrets Manager.

Generic handler that processes SecretMapping objects.  No service-specific
``if`` branches.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from core.manifest_reader import SecretMapping

logger = logging.getLogger(__name__)


def fetch_and_write_secret(
    mapping: SecretMapping,
    secrets_client: Any,
    prefix: str,
    env: str,
    service: str,
) -> Path:
    """Fetch a single secret from Secrets Manager and write to target path.

    Supports interpolation of {{prefix}}, {{env}}, {{service}} in both
    source and target.
    """
    source = mapping.source.format(prefix=prefix, env=env, service=service)
    target = mapping.target.format(prefix=prefix, env=env, service=service)

    logger.info(f"📥 Fetching secret: {{source}}")
    response = secrets_client.get_secret_value(SecretId=source)
    content = response["SecretString"]

    if mapping.format == "extract-key" and mapping.extract_key:
        content = _extract_key(content, mapping.extract_key)
    elif mapping.format == "dotenv":
        pass  # Write as-is for dotenv format

    target_path = Path(target)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(content, encoding="utf-8")
    logger.info(f"✅ Secret written to: {{target_path}}")
    return target_path


def fetch_all_secrets(
    secrets: tuple[SecretMapping, ...],
    secrets_client: Any,
    prefix: str,
    env: str,
    service: str,
) -> list[Path]:
    """Fetch all secrets for a service."""
    paths: list[Path] = []
    for mapping in secrets:
        try:
            path = fetch_and_write_secret(mapping, secrets_client, prefix, env, service)
            paths.append(path)
        except Exception as e:
            logger.error(f"❌ Failed to fetch secret {{mapping.source}}: {{e}}")
            raise
    return paths


def _extract_key(content: str, key: str) -> str:
    """Extract a specific key from JSON or dotenv secret content."""
    s = content.strip()
    try:
        parsed = json.loads(s)
        if isinstance(parsed, dict) and key in parsed:
            return str(parsed[key]).strip()
    except (json.JSONDecodeError, ValueError):
        pass
    for line in s.splitlines():
        line = line.strip()
        if "=" in line:
            k, v = line.split("=", 1)
            if k.strip() == key:
                return v.strip().strip("\\"\\'")
    return s
'''


def _gen_ecs_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""ECS Fargate deployment engine.

Builds Docker images, pushes to ECR, registers task definitions, and updates
ECS services.  Completely generic — driven entirely by DeploymentProfile.
"""

from __future__ import annotations

import base64
import json
import logging
import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

from core.conventions import DeploymentProfile
from core.secrets import fetch_all_secrets

logger = logging.getLogger(__name__)


class EcsEngine:
    """Generic ECS Fargate deployment engine."""

    def __init__(self, profile: DeploymentProfile, environment: str, prefix: str, session: Any):
        self.profile = profile
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.iac_outputs = self._load_iac_outputs()

    def build_and_push(self) -> str:
        """Build Docker image and push to ECR.  Returns the full image URI."""
        logger.info(f"🏗️ Building and pushing {{self.profile.name}}...")

        # 1. Fetch secrets
        secrets_client = self.session.client("secretsmanager")
        fetch_all_secrets(
            self.profile.secrets, secrets_client,
            self.prefix, self.env, self.profile.name,
        )

        # 2. Get ECR repo
        ecr_client = self.session.client("ecr")
        repo_name = f"{{self.prefix}}-{{self.env}}-{{self.profile.name}}"
        repo_uri = self._get_ecr_repo_uri(ecr_client, repo_name)

        # 3. ECR login
        self._ecr_login(ecr_client)

        # 4. Build and push
        git_sha = self._get_git_sha()
        image_uri = f"{{repo_uri}}:{{git_sha}}"

        env = os.environ.copy()
        env["DOCKER_BUILDKIT"] = "1"

        build_args = [
            "docker", "buildx", "build",
            "--progress=plain",
            "-f", str(self.profile.dockerfile),
            "-t", image_uri,
            "--push",
            "--cache-from", f"type=registry,ref={{repo_uri}}:buildcache",
            "--cache-to", f"type=registry,ref={{repo_uri}}:buildcache,mode=max",
            str(self.profile.build_context),
        ]

        logger.info(f"Running: {{' '.join(build_args)}}")
        subprocess.run(build_args, check=True, env=env)
        logger.info(f"✅ Image pushed: {{image_uri}}")
        return image_uri

    def deploy(self, image_uri: str | None = None) -> None:
        """Update ECS service with a new task definition."""
        logger.info(f"🚀 Deploying {{self.profile.name}} to ECS...")

        if image_uri is None:
            image_uri = self._calculate_image_uri()

        ecs_client = self.session.client("ecs")
        cluster = f"{{self.prefix}}-{{self.env}}-cluster"

        task_def = self._build_task_definition(image_uri)
        result = ecs_client.register_task_definition(**task_def)
        task_def_arn = result["taskDefinition"]["taskDefinitionArn"]

        desired_count = self._get_output(f"ecs_services.{{self.profile.name}}.compute_config.desired_count")
        if desired_count is None:
            raise ValueError(f"Missing IaC output: ecs_services.{{self.profile.name}}.compute_config.desired_count")

        ecs_client.update_service(
            cluster=cluster,
            service=self.profile.name,
            taskDefinition=task_def_arn,
            desiredCount=desired_count,
            forceNewDeployment=self.profile.has_sidecars,
        )

        self._wait_for_deployment(ecs_client, cluster, self.profile.name)
        logger.info(f"✅ {{self.profile.name}} deployed successfully")

    # ── Internal helpers ──────────────────────────────────────────────

    def _build_task_definition(self, image_uri: str) -> dict[str, Any]:
        svc = self.profile.name
        cpu = self._require_output(f"ecs_services.{{svc}}.compute_config.cpu")
        memory = self._require_output(f"ecs_services.{{svc}}.compute_config.memory")
        exec_role = self._require_output(f"ecs_services.{{svc}}.execution_role_arn")
        task_role = self._require_output(f"ecs_services.{{svc}}.task_role_arn")
        log_group = self._require_output(f"ecs_services.{{svc}}.log_group_name")
        container_config = self._require_output(f"ecs_services.{{svc}}.container_config")
        container_port = container_config["port"]
        aws_region = self.session.region_name

        env_vars = [
            {{"name": "ENV", "value": self.env}},
            {{"name": "PLATFORM_PREFIX", "value": self.prefix}},
        ]
        if self.profile.type == "spring-boot":
            env_vars.append({{"name": "SPRING_PROFILES_ACTIVE", "value": self.env}})
        tf_env = container_config.get("environment")
        if isinstance(tf_env, dict):
            env_vars.extend({{"name": k, "value": v}} for k, v in tf_env.items())
        elif isinstance(tf_env, list):
            env_vars.extend(tf_env)

        main_container = {{
            "name": svc,
            "image": image_uri,
            "essential": True,
            "portMappings": [{{"containerPort": container_port, "protocol": "tcp"}}],
            "environment": env_vars,
            "logConfiguration": {{
                "logDriver": "awslogs",
                "options": {{
                    "awslogs-group": log_group,
                    "awslogs-region": aws_region,
                    "awslogs-stream-prefix": "ecs",
                }},
            }},
        }}

        containers = [main_container]

        # Add sidecars from profile (e.g., OpenFGA)
        for sc_name, sc_config in self.profile.sidecars.items():
            sidecar = {{
                "name": sc_name,
                "image": sc_config.image,
                "essential": False,
                "cpu": sc_config.cpu,
                "memory": sc_config.memory,
                "memoryReservation": sc_config.cpu,
                "logConfiguration": {{
                    "logDriver": "awslogs",
                    "options": {{
                        "awslogs-group": log_group,
                        "awslogs-region": aws_region,
                        "awslogs-stream-prefix": sc_name,
                    }},
                }},
            }}
            if sc_config.port:
                sidecar["portMappings"] = [{{"containerPort": sc_config.port, "protocol": "tcp"}}]
            if sc_config.command:
                sidecar["command"] = list(sc_config.command)
            if sc_config.environment:
                sidecar["environment"] = [{{"name": k, "value": v}} for k, v in sc_config.environment.items()]
            containers.append(sidecar)

        task_def: dict[str, Any] = {{
            "family": f"{{self.prefix}}-{{self.env}}-{{svc}}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": str(cpu),
            "memory": str(memory),
            "executionRoleArn": exec_role,
            "taskRoleArn": task_role,
            "containerDefinitions": containers,
        }}

        # EFS volumes
        efs_info = self._get_output(f"ecs_services.{{svc}}.efs")
        if efs_info and isinstance(efs_info, dict):
            fs_id = efs_info.get("file_system_id")
            if fs_id:
                vol_name = f"{{svc}}-efs"
                vol = {{
                    "name": vol_name,
                    "efsVolumeConfiguration": {{
                        "fileSystemId": fs_id,
                        "rootDirectory": efs_info.get("root_directory", "/"),
                        "transitEncryption": "ENABLED",
                    }},
                }}
                ap_id = efs_info.get("access_point_id") or efs_info.get("access_point")
                if ap_id:
                    vol["efsVolumeConfiguration"]["authorizationConfig"] = {{
                        "accessPointId": ap_id, "iam": "ENABLED",
                    }}
                task_def["volumes"] = [vol]
                mount_path = efs_info.get("mount_path", f"/mnt/{{svc}}")
                main_container["mountPoints"] = [{{
                    "sourceVolume": vol_name,
                    "containerPath": mount_path,
                    "readOnly": False,
                }}]
                env_vars.append({{"name": "EFS_MOUNT_PATH", "value": mount_path}})

        return task_def

    def _calculate_image_uri(self) -> str:
        ecr_client = self.session.client("ecr")
        repo_name = f"{{self.prefix}}-{{self.env}}-{{self.profile.name}}"
        repo_uri = self._get_ecr_repo_uri(ecr_client, repo_name)
        git_sha = self._get_git_sha()
        return f"{{repo_uri}}:{{git_sha}}"

    def _get_ecr_repo_uri(self, ecr_client: Any, repo_name: str) -> str:
        response = ecr_client.describe_repositories(repositoryNames=[repo_name])
        return response["repositories"][0]["repositoryUri"]

    def _ecr_login(self, ecr_client: Any) -> None:
        token_resp = ecr_client.get_authorization_token()
        token = token_resp["authorizationData"][0]["authorizationToken"]
        endpoint = token_resp["authorizationData"][0]["proxyEndpoint"]
        username, password = base64.b64decode(token).decode().split(":")
        proc = subprocess.run(
            ["docker", "login", "--username", username, "--password-stdin", endpoint],
            input=password, text=True, capture_output=True, check=True,
        )

    def _wait_for_deployment(self, ecs_client: Any, cluster: str, service: str, timeout: int = 600) -> None:
        logger.info("⏳ Waiting for deployment to stabilize...")
        start = time.time()
        while time.time() - start < timeout:
            resp = ecs_client.describe_services(cluster=cluster, services=[service])
            svc = resp["services"][0]
            primary = next((d for d in svc["deployments"] if d["status"] == "PRIMARY"), None)
            if primary and primary["runningCount"] == primary["desiredCount"]:
                return
            time.sleep(30)
        raise TimeoutError(f"Deployment of {{service}} did not stabilize in {{timeout}}s")

    def _load_iac_outputs(self) -> dict[str, Any]:
        path = Path("iac-outputs/iac-outputs.json")
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
        return {{}}

    def _get_output(self, dotpath: str, default: Any = None) -> Any:
        value = self.iac_outputs
        for key in dotpath.split("."):
            if isinstance(value, dict) and key in value:
                v = value[key]
                if isinstance(v, dict) and "value" in v and "type" in v:
                    value = v["value"]
                else:
                    value = v
            else:
                return default
        return value

    def _require_output(self, dotpath: str) -> Any:
        val = self._get_output(dotpath)
        if val is None:
            raise ValueError(f"❌ Missing required IaC output: {{dotpath}}")
        return val

    @staticmethod
    def _get_git_sha() -> str:
        try:
            return subprocess.run(
                ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True,
            ).stdout.strip()
        except subprocess.CalledProcessError:
            return "unknown"
'''


def _gen_s3_static_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""S3 + CloudFront static site deployment engine.

Builds the static site, syncs to S3, and invalidates CloudFront.
Completely generic — driven by DeploymentProfile.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Any

from core.conventions import DeploymentProfile
from core.secrets import fetch_all_secrets

logger = logging.getLogger(__name__)


class S3StaticEngine:
    """Generic S3 + CloudFront static site deployment engine."""

    def __init__(self, profile: DeploymentProfile, environment: str, prefix: str, session: Any):
        self.profile = profile
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.iac_outputs = self._load_iac_outputs()

    def build_and_deploy(self) -> None:
        """Build the static site, sync to S3, and invalidate CDN."""
        logger.info(f"🏗️ Building and deploying {{self.profile.name}} (s3-static)...")

        # 1. Fetch secrets
        secrets_client = self.session.client("secretsmanager")
        fetch_all_secrets(
            self.profile.secrets, secrets_client,
            self.prefix, self.env, self.profile.name,
        )

        # 2. Install dependencies
        logger.info("📦 Installing dependencies...")
        subprocess.run(["pnpm", "install", "--frozen-lockfile"], check=True)

        # 3. Build
        logger.info(f"🔨 Building {{self.profile.name}}...")
        build_dir = Path(self.profile.build_context)
        subprocess.run(
            ["pnpm", "--filter", self.profile.name, "build"],
            check=True, cwd=build_dir if build_dir != Path(".") else None,
        )

        # 4. Find output directory
        output_dir = self._find_output_dir()

        # 5. Sync to S3
        bucket = f"{{self.prefix}}-{{self.env}}-{{self.profile.name}}-static"
        self._sync_to_s3(output_dir, bucket)

        # 6. Invalidate CDN
        if self.profile.cdn:
            self._invalidate_cdn()

        logger.info(f"✅ {{self.profile.name}} deployed to S3")

    def _find_output_dir(self) -> Path:
        """Find the build output directory for the static site."""
        structure = Path("foundry.json")  # We're in repo root
        manifest_data = json.loads(structure.read_text(encoding="utf-8"))
        apps_dir = manifest_data.get("structure", {{}}).get("appsDir", "apps")
        # Next.js static export → out/, Vite → dist/
        for candidate in ["out", "dist", "build"]:
            p = Path(apps_dir) / "frontend" / self.profile.name / candidate
            if p.exists():
                return p
        raise FileNotFoundError(f"Could not find build output for {{self.profile.name}}")

    def _sync_to_s3(self, output_dir: Path, bucket: str) -> None:
        logger.info(f"📤 Syncing {{output_dir}} → s3://{{bucket}}/")
        s3_client = self.session.client("s3")
        for file_path in output_dir.rglob("*"):
            if file_path.is_file():
                key = str(file_path.relative_to(output_dir)).replace("\\\\", "/")
                content_type = self._guess_content_type(key)
                s3_client.upload_file(
                    str(file_path), bucket, key,
                    ExtraArgs={{"ContentType": content_type}},
                )
        logger.info(f"✅ Synced to s3://{{bucket}}/")

    def _invalidate_cdn(self) -> None:
        dist_id = self._get_distribution_id()
        if not dist_id:
            logger.warning("⚠️ No CloudFront distribution ID found — skipping invalidation")
            return
        cf_client = self.session.client("cloudfront")
        cf_client.create_invalidation(
            DistributionId=dist_id,
            InvalidationBatch={{
                "Paths": {{"Quantity": 1, "Items": ["/*"]}},
                "CallerReference": f"deploy-{{int(time.time())}}",
            }},
        )
        logger.info(f"✅ CloudFront invalidation created for {{dist_id}}")

    def _get_distribution_id(self) -> str | None:
        # Try IaC outputs
        dist_id = self._get_output(
            f"ecs_services.{{self.profile.name}}.cloudfront.distribution_id"
        )
        if dist_id:
            return dist_id
        # Fallback: try frontend-specific output path
        dist_id = self._get_output(
            f"cloudfront_distributions.{{self.profile.name}}.distribution_id"
        )
        return dist_id

    def _load_iac_outputs(self) -> dict[str, Any]:
        path = Path("iac-outputs/iac-outputs.json")
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
        return {{}}

    def _get_output(self, dotpath: str, default: Any = None) -> Any:
        value = self.iac_outputs
        for key in dotpath.split("."):
            if isinstance(value, dict) and key in value:
                v = value[key]
                if isinstance(v, dict) and "value" in v and "type" in v:
                    value = v["value"]
                else:
                    value = v
            else:
                return default
        return value

    @staticmethod
    def _guess_content_type(key: str) -> str:
        ext = key.rsplit(".", 1)[-1].lower() if "." in key else ""
        return {{
            "html": "text/html",
            "css": "text/css",
            "js": "application/javascript",
            "json": "application/json",
            "png": "image/png",
            "jpg": "image/jpeg",
            "jpeg": "image/jpeg",
            "svg": "image/svg+xml",
            "ico": "image/x-icon",
            "woff2": "font/woff2",
            "woff": "font/woff",
            "ttf": "font/ttf",
            "txt": "text/plain",
            "xml": "application/xml",
            "webp": "image/webp",
        }}.get(ext, "application/octet-stream")
'''


def _gen_iac_engine(manifest: ProjectManifest, header: str) -> str:
    iac = manifest.data.get("ci", {}).get("iac", "opentofu")
    binary = "tofu" if iac == "opentofu" else "terraform"
    iac_dir = manifest.data.get("ci", {}).get("iacDir", "ci/iac")

    return f'''{header}
"""IaC engine — runs OpenTofu/Terraform plan and apply.

Reads the IaC directory from the manifest and runs the appropriate binary.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

IAC_BINARY = "{binary}"
IAC_DIR = "{iac_dir}"


class IacEngine:
    """Runs IaC (OpenTofu/Terraform) operations."""

    def __init__(self, environment: str, prefix: str, session: Any):
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.work_dir = Path(IAC_DIR) / self.env

    def plan(self) -> None:
        """Run IaC plan."""
        logger.info(f"📋 Running {{IAC_BINARY}} plan in {{self.work_dir}}...")
        self._run(["init", "-input=false"])
        self._run(["plan", "-input=false", "-out=tfplan"])

    def apply(self) -> None:
        """Run IaC apply."""
        logger.info(f"🚀 Running {{IAC_BINARY}} apply in {{self.work_dir}}...")
        self._run(["apply", "-input=false", "-auto-approve", "tfplan"])

    def plan_apply(self) -> None:
        """Run plan then apply."""
        self.plan()
        self.apply()

    def save_outputs(self) -> Path:
        """Save IaC outputs to iac-outputs/iac-outputs.json."""
        logger.info("💾 Saving IaC outputs...")
        result = subprocess.run(
            [IAC_BINARY, "output", "-json"],
            capture_output=True, text=True, check=True,
            cwd=self.work_dir,
        )
        outputs = json.loads(result.stdout)
        out_dir = Path("iac-outputs")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / "iac-outputs.json"
        out_file.write_text(json.dumps(outputs, indent=2), encoding="utf-8")
        logger.info(f"✅ Outputs saved to {{out_file}}")
        return out_file

    def _run(self, args: list[str]) -> None:
        cmd = [IAC_BINARY] + args
        logger.info(f"Running: {{' '.join(cmd)}} (in {{self.work_dir}})")
        subprocess.run(cmd, check=True, cwd=self.work_dir)
'''


def _gen_database_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Database migration engine — runs Liquibase migrations.

Reads the databases block from foundry.json and runs migrations for each
database that needs updating.
"""

from __future__ import annotations

import json
import logging
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class DatabaseEngine:
    """Runs Liquibase database migrations."""

    def __init__(self, environment: str, prefix: str, session: Any):
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.manifest = json.loads(Path("foundry.json").read_text(encoding="utf-8"))

    def migrate_all(self) -> None:
        """Run migrations for all databases in the manifest."""
        databases = self.manifest.get("databases", {{}})
        for db_name, db_config in databases.items():
            self.migrate(db_name, db_config)

    def migrate(self, db_name: str, db_config: dict[str, Any]) -> None:
        """Run Liquibase migration for a single database."""
        engine = db_config.get("engine", "mariadb")
        changelog = db_config.get("changelog")
        properties = db_config.get("properties")

        if not changelog:
            logger.warning(f"⚠️ No changelog for database {{db_name}} — skipping")
            return

        logger.info(f"🗄️ Migrating database: {{db_name}} ({{engine}})")

        args = [
            "liquibase",
            f"--changelog-file={{changelog}}",
            "update",
        ]
        if properties:
            args.insert(1, f"--defaults-file={{properties}}")

        logger.info(f"Running: {{' '.join(args)}}")
        subprocess.run(args, check=True)
        logger.info(f"✅ Database {{db_name}} migrated successfully")
'''


def _gen_change_detector(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Change detector — determines which services need deployment.

Uses git diff to find changed files and maps them to services using
watch paths from the convention engine.
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from typing import Any

from core.conventions import DeploymentProfile, resolve_all_profiles
from core.manifest_reader import Manifest

logger = logging.getLogger(__name__)


def detect_changes(
    git_before: str,
    git_after: str,
    branch: str,
    force: str = "",
) -> dict[str, Any]:
    """Detect which services changed and need deployment.

    Returns a dict with:
      - services: list of service names that changed
      - environment: resolved environment name
      - has_db_changes: whether any database changelog paths changed
    """
    manifest = Manifest.load()
    environment = manifest.resolve_environment(branch)

    if not environment:
        logger.info(f"ℹ️ Branch '{{branch}}' does not map to any environment — skipping")
        return {{"services": [], "environment": "", "has_db_changes": "false"}}

    profiles = resolve_all_profiles(manifest)

    # Force-deploy specific services
    if force:
        forced = [s.strip() for s in force.split(",") if s.strip()]
        logger.info(f"⚡ Force deploying: {{forced}}")
        return {{
            "services": forced,
            "environment": environment,
            "has_db_changes": str(any(
                profiles.get(s, None) and profiles[s].database for s in forced
            )).lower(),
        }}

    # Get changed files
    changed_files = _get_changed_files(git_before, git_after)
    if not changed_files:
        logger.info("ℹ️ No files changed")
        return {{"services": [], "environment": environment, "has_db_changes": "false"}}

    logger.info(f"📝 {{len(changed_files)}} files changed")

    # Match to services
    affected: list[str] = []
    for name, profile in profiles.items():
        if not profile.is_deployable:
            continue
        for pattern in profile.watch_paths:
            if any(re.match(pattern, f) for f in changed_files):
                affected.append(name)
                break

    # Check for IaC changes (deploys everything)
    ci_dir = manifest.ci.get("iacDir", "ci/iac")
    if any(f.startswith(f"{{ci_dir}}/") for f in changed_files):
        logger.info("🏗️ IaC changes detected — all services will deploy")
        affected = [n for n, p in profiles.items() if p.is_deployable]

    # Check for database changes
    db_paths = [db.get("changelog", "").rsplit("/", 1)[0] for db in manifest.databases.values()]
    has_db_changes = any(
        any(f.startswith(dp) for dp in db_paths if dp)
        for f in changed_files
    )

    logger.info(f"🎯 Affected services: {{affected}}")
    return {{
        "services": affected,
        "environment": environment,
        "has_db_changes": str(has_db_changes).lower(),
    }}


def _get_changed_files(before: str, after: str) -> list[str]:
    """Get list of changed files between two git commits."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", before, after],
            capture_output=True, text=True, check=True,
        )
        return [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
    except subprocess.CalledProcessError as e:
        logger.warning(f"⚠️ git diff failed: {{e}}")
        return []


def write_github_outputs(result: dict[str, Any]) -> None:
    """Write detection results to GITHUB_OUTPUT if running in Actions."""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if not github_output:
        logger.info("ℹ️ Not in GitHub Actions — printing results to stdout")
        print(json.dumps(result, indent=2))
        return

    with open(github_output, "a") as f:
        f.write(f"services={{json.dumps(result['services'])}}\\n")
        f.write(f"environment={{result['environment']}}\\n")
        f.write(f"has_db_changes={{result['has_db_changes']}}\\n")

    logger.info(f"✅ GitHub outputs written: {{len(result['services'])}} services, env={{result['environment']}}")
'''


def _gen_deploy_cli(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Unified deployment CLI.

Single entry point for all deployment operations:
  deploy.py detect   — detect changed services
  deploy.py iac      — run IaC plan/apply
  deploy.py migrate  — run database migrations
  deploy.py service  — deploy a single service
  deploy.py all      — deploy everything
"""

from __future__ import annotations

import logging
import sys

import boto3
import click

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


@click.group()
def cli():
    """Foundry deployment CLI — manifest-driven, convention-based."""
    pass


@cli.command()
@click.option("--git-before", required=True, help="Git SHA before the push")
@click.option("--git-after", required=True, help="Git SHA after the push")
@click.option("--branch", required=True, help="Git branch name")
@click.option("--force", default="", help="Comma-separated service names to force deploy")
def detect(git_before: str, git_after: str, branch: str, force: str):
    """Detect which services need deployment based on git changes."""
    from orchestration.change_detector import detect_changes, write_github_outputs

    result = detect_changes(git_before, git_after, branch, force)
    write_github_outputs(result)


@cli.command()
@click.option("--environment", required=True, help="Target environment (prod, dev, test)")
@click.option("--operation", required=True,
              type=click.Choice(["plan", "apply", "plan-apply"]),
              help="IaC operation")
def iac(environment: str, operation: str):
    """Run IaC (OpenTofu/Terraform) operations."""
    from engines.iac_engine import IacEngine
    from core.manifest_reader import Manifest

    manifest = Manifest.load()
    session = boto3.Session()
    engine = IacEngine(environment, manifest.prefix, session)

    if operation == "plan":
        engine.plan()
    elif operation == "apply":
        engine.apply()
    elif operation == "plan-apply":
        engine.plan_apply()

    engine.save_outputs()


@cli.command()
@click.option("--environment", required=True, help="Target environment")
def migrate(environment: str):
    """Run database migrations for all databases."""
    from engines.database_engine import DatabaseEngine

    session = boto3.Session()
    from core.manifest_reader import Manifest
    manifest = Manifest.load()
    engine = DatabaseEngine(environment, manifest.prefix, session)
    engine.migrate_all()


@cli.command()
@click.option("--name", required=True, help="Service name from foundry.json")
@click.option("--environment", required=True, help="Target environment")
@click.option("--operation", required=True,
              type=click.Choice(["build-push", "deploy", "build-deploy"]),
              help="Operation to perform")
def service(name: str, environment: str, operation: str):
    """Deploy a single service."""
    from core.conventions import resolve_all_profiles
    from core.manifest_reader import Manifest
    from engines.ecs_engine import EcsEngine
    from engines.s3_static_engine import S3StaticEngine

    manifest = Manifest.load()
    profiles = resolve_all_profiles(manifest)

    if name not in profiles:
        logger.error(f"❌ Unknown service: {{name}}")
        sys.exit(1)

    profile = profiles[name]
    session = boto3.Session()

    if profile.strategy == "ecs":
        engine = EcsEngine(profile, environment, manifest.prefix, session)
        if operation == "build-push":
            engine.build_and_push()
        elif operation == "deploy":
            engine.deploy()
        elif operation == "build-deploy":
            image_uri = engine.build_and_push()
            engine.deploy(image_uri)

    elif profile.strategy == "s3-static":
        engine = S3StaticEngine(profile, environment, manifest.prefix, session)
        if operation in ("build-deploy",):
            engine.build_and_deploy()
        else:
            logger.warning(f"⚠️ Operation '{{operation}}' not applicable for s3-static strategy")

    else:
        logger.error(f"❌ Service {{name}} has strategy '{{profile.strategy}}' — not deployable")
        sys.exit(1)

    logger.info("🎉 Operation completed successfully")


@cli.command(name="all")
@click.option("--environment", required=True, help="Target environment")
def deploy_all(environment: str):
    """Deploy all services (force full deployment)."""
    from core.conventions import resolve_all_profiles
    from core.manifest_reader import Manifest

    manifest = Manifest.load()
    profiles = resolve_all_profiles(manifest)

    deployable = {{n: p for n, p in profiles.items() if p.is_deployable}}
    logger.info(f"🚀 Deploying all {{len(deployable)}} services to {{environment}}")

    # TODO: respect dependency ordering
    for name, profile in sorted(deployable.items()):
        logger.info(f"\\n{'=' * 60}")
        logger.info(f"Deploying {{name}} ({{profile.strategy}})")
        logger.info(f"{'=' * 60}")
        # Each service deploy is done via the 'service' command logic
        # For now, call it directly
        from click.testing import CliRunner
        runner = CliRunner()
        if profile.strategy == "ecs":
            runner.invoke(service, ["--name", name, "--environment", environment, "--operation", "build-deploy"])
        elif profile.strategy == "s3-static":
            runner.invoke(service, ["--name", name, "--environment", environment, "--operation", "build-deploy"])


if __name__ == "__main__":
    cli()
'''


# ── Registry of all files to generate ────────────────────────────────────

_FILE_GENERATORS: dict[str, Any] = {
    "requirements.txt": _gen_requirements,
    "deploy.py": _gen_deploy_cli,
    "core/__init__.py": _gen_core_init,
    "core/manifest_reader.py": _gen_manifest_reader,
    "core/conventions.py": _gen_conventions,
    "core/secrets.py": _gen_secrets,
    "engines/__init__.py": _gen_engines_init,
    "engines/ecs_engine.py": _gen_ecs_engine,
    "engines/s3_static_engine.py": _gen_s3_static_engine,
    "engines/iac_engine.py": _gen_iac_engine,
    "engines/database_engine.py": _gen_database_engine,
    "orchestration/__init__.py": _gen_orchestration_init,
    "orchestration/change_detector.py": _gen_change_detector,
}


__all__ = [
    "generate_scripts",
]
