"""Scripts generator — produces the complete ``ci/scripts/`` directory from the manifest.

This module generates every Python file in ``ci/scripts/`` including:

- ``core/`` — manifest reader, convention engine, secrets handler
- ``engines/`` — ECS, S3 static, IaC, and database migration engines
- ``orchestration/`` — change detector, dependency graph, coordinator
- ``deploy.py`` — unified CLI entry point
- ``requirements.txt`` — pinned dependencies

All generated files are self-contained — they do NOT depend on the Foundry CLI
at runtime.  They read ``foundry.json`` directly and resolve deployment profiles
using an embedded copy of the convention engine.
"""

from __future__ import annotations

import shutil
from pathlib import Path
from typing import Any

from foundry_cli.core.project.manifest import ProjectManifest

# ── Header for all generated files ───────────────────────────────────────

_HEADER = '''\
# ════════════════════════════════════════════════════════════════════════════
# GENERATED BY: foundry generate scripts
# Manual edits may break regeneration — edit with intention.
# Regenerate with: foundry generate scripts --clean
# Source: foundry.json (schemaVersion {schema_version})
# ════════════════════════════════════════════════════════════════════════════
'''


def generate_scripts(manifest: ProjectManifest, output_dir: Path, *, clean: bool = False) -> list[Path]:
    """Generate the complete ``ci/scripts/`` directory tree.

    Args:
        manifest: A loaded ``ProjectManifest``.
        output_dir: Absolute path to the target ``ci/scripts/`` directory.
        clean: If ``True``, delete and recreate the directory from scratch.

    Returns:
        List of all generated file paths.
    """
    schema_version = manifest.data.get("schemaVersion", "0.3.0")
    header = _HEADER.format(schema_version=schema_version)

    if clean and output_dir.exists():
        shutil.rmtree(output_dir)

    output_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []

    # Generate each module
    for rel_path, content_fn in _FILE_GENERATORS.items():
        file_path = output_dir / rel_path
        file_path.parent.mkdir(parents=True, exist_ok=True)
        content = content_fn(manifest, header)
        file_path.write_text(content, encoding="utf-8")
        generated.append(file_path)

    return generated


# ── File content generators ──────────────────────────────────────────────
# Each function takes (manifest, header) and returns the full file content.


def _gen_requirements(manifest: ProjectManifest, header: str) -> str:
    return f"""{header}
boto3>=1.34.0
click>=8.1.0
"""


def _gen_core_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Core modules for manifest-driven deployment."""\n'


def _gen_engines_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Deployment engines — one per deployment strategy."""\n'


def _gen_orchestration_init(manifest: ProjectManifest, header: str) -> str:
    return f'{header}\n"""Orchestration — change detection, dependency ordering, coordination."""\n'


def _gen_manifest_reader(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Reads foundry.json and resolves deployment profiles.

This is a self-contained manifest reader — it does NOT depend on the
Foundry CLI.  It reads the raw JSON and delegates to the convention engine.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class SecretMapping:
    """Maps a Secrets Manager secret to a file in the build context."""
    source: str
    target: str
    format: str = "raw"
    extract_key: str | None = None
    optional: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SecretMapping":
        return cls(
            source=data["source"],
            target=data["target"],
            format=data.get("format", "raw"),
            extract_key=data.get("extractKey"),
            optional=data.get("optional", False),
        )


@dataclass(frozen=True)
class SidecarHealthCheck:
    """ECS container health check configuration."""
    command: str
    interval: int = 30
    timeout: int = 5
    retries: int = 3
    start_period: int = 60

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SidecarHealthCheck":
        return cls(
            command=data["command"],
            interval=data.get("interval", 30),
            timeout=data.get("timeout", 5),
            retries=data.get("retries", 3),
            start_period=data.get("startPeriod", 60),
        )


@dataclass(frozen=True)
class SidecarDeployConfig:
    """ECS sidecar container configuration."""
    image: str
    port: int | None = None
    cpu: int = 128
    memory: int = 256
    essential: bool = False
    command: tuple[str, ...] = field(default_factory=tuple)
    environment: dict[str, str] = field(default_factory=dict)
    health_check: SidecarHealthCheck | None = None

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SidecarDeployConfig":
        hc_data = data.get("healthCheck")
        return cls(
            image=data["image"],
            port=data.get("port"),
            cpu=data.get("cpu", 128),
            memory=data.get("memory", 256),
            essential=data.get("essential", False),
            command=tuple(data.get("command", [])),
            environment=dict(data.get("environment", {{}})),
            health_check=SidecarHealthCheck.from_dict(hc_data) if hc_data else None,
        )


@dataclass(frozen=True)
class CdnConfig:
    """CDN configuration for static/frontend deployments."""
    distribution_id_output: str | None = None
    invalidation_paths: tuple[str, ...] = ("/*",)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "CdnConfig":
        paths = data.get("invalidationPaths", ["/*"])
        return cls(
            distribution_id_output=data.get("distributionIdOutput"),
            invalidation_paths=tuple(paths) if isinstance(paths, list) else ("/*",),
        )


@dataclass(frozen=True)
class DeployConfig:
    """Deployment configuration overrides."""
    strategy: str | None = None
    dockerfile: str | None = None
    build_context: str | None = None
    build_command: str | None = None
    secrets: tuple[SecretMapping, ...] = field(default_factory=tuple)
    cdn: bool | CdnConfig | None = None
    depends_on: tuple[str, ...] = field(default_factory=tuple)
    sidecars: dict[str, SidecarDeployConfig] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DeployConfig":
        raw_secrets = data.get("secrets", [])
        secrets = tuple(SecretMapping.from_dict(s) for s in raw_secrets if isinstance(s, dict))
        raw_cdn = data.get("cdn")
        cdn: bool | CdnConfig | None = None
        if isinstance(raw_cdn, bool):
            cdn = raw_cdn
        elif isinstance(raw_cdn, dict):
            cdn = CdnConfig.from_dict(raw_cdn)
        raw_sidecars = data.get("sidecars", {{}})
        sidecars = {{}}
        if isinstance(raw_sidecars, dict):
            for name, sc_data in raw_sidecars.items():
                if isinstance(sc_data, dict):
                    sidecars[name] = SidecarDeployConfig.from_dict(sc_data)
        return cls(
            strategy=data.get("strategy"),
            dockerfile=data.get("dockerfile"),
            build_context=data.get("buildContext"),
            build_command=data.get("buildCommand"),
            secrets=secrets,
            cdn=cdn,
            depends_on=tuple(data.get("dependsOn", [])),
            sidecars=sidecars,
        )


@dataclass(frozen=True)
class ServiceConfig:
    """Lean service definition from foundry.json.

    v0.5.0: ``scope``, ``stack`` (type/framework/language), ``deploy`` (strategy),
            ``run`` (port/args), ``database`` (inline).
    v0.4.0 compat: ``kind``→stack.type, ``type``→stack.framework, ``role``→scope.
    """
    kind: str | None = None          # stack.type (backend/frontend/package)
    type: str | None = None          # stack.framework (spring-boot, nextjs, etc.)
    role: str | None = None          # scope (public/internal)
    database: str | dict[str, Any] | None = None
    deploy: DeployConfig | None = None

    # --- helper properties ---------------------------------------------------

    @property
    def database_name(self) -> str | None:
        """Logical database name (service name when inline dict, string ref otherwise)."""
        if isinstance(self.database, dict):
            return None  # caller must use the service name as db_name
        return self.database

    @property
    def database_config(self) -> dict[str, Any] | None:
        """Database config dict when declared inline; ``None`` for string refs."""
        return self.database if isinstance(self.database, dict) else None

    @property
    def strategy(self) -> str | None:
        """Deployment strategy from the deploy block."""
        return self.deploy.strategy if self.deploy else None

    @property
    def effective_strategy(self) -> str | None:
        """Deploy block strategy (normalised: ecs→service, s3-static→static)."""
        raw = self.deploy.strategy if self.deploy else None
        if not raw:
            return None
        return {{"ecs": "service", "s3-static": "static"}}.get(raw, raw)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ServiceConfig":
        # ── Stack resolution ─────────────────────────────────────────
        stack = data.get("stack", {{}})
        if isinstance(stack, dict) and stack:
            stack_type = stack.get("type")
            stack_framework = stack.get("framework")
        else:
            stack_type = data.get("kind")
            stack_framework = data.get("type")

        # ── Scope → role ─────────────────────────────────────────────
        scope = data.get("scope") or data.get("role")

        # ── Deploy block ─────────────────────────────────────────────
        deploy = None
        if "deploy" in data and isinstance(data["deploy"], dict):
            deploy = DeployConfig.from_dict(data["deploy"])
        elif data.get("strategy"):
            # v0.4.0 flat strategy → synthesize a DeployConfig
            deploy = DeployConfig(strategy=data["strategy"])

        return cls(
            kind=stack_type,
            type=stack_framework,
            role=scope,
            database=data.get("database"),
            deploy=deploy,
        )


@dataclass(frozen=True)
class StructureConfig:
    """Directory layout from the structure block."""
    apps_dir: str = "apps"
    ci_dir: str = "ci"
    packages_dir: str = "packages"

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StructureConfig":
        return cls(
            apps_dir=data.get("appsDir", "apps"),
            ci_dir=data.get("ciDir", "ci"),
            packages_dir=data.get("packagesDir", "packages"),
        )


@dataclass(frozen=True)
class EnvironmentConfig:
    """Maps a deployment environment to a Git branch."""
    branch: str
    enabled: bool = True
    auto_approve: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EnvironmentConfig":
        return cls(
            branch=data["branch"],
            enabled=data.get("enabled", True),
            auto_approve=data.get("autoApprove", False),
        )


class Manifest:
    """Parsed foundry.json with convenience accessors."""

    def __init__(self, data: dict[str, Any]):
        self.data = data

    @classmethod
    def load(cls, path: Path | None = None) -> "Manifest":
        if path is None:
            path = Path("foundry.json")
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls(data)

    @property
    def name(self) -> str:
        return self.data.get("name", "")

    @property
    def prefix(self) -> str:
        # v0.4.0: top-level prefix
        if p := self.data.get("prefix"):
            return p
        # v0.3.0 fallback: ecosystem.prefix
        eco = self.data.get("ecosystem", {{}})
        if p := eco.get("prefix"):
            return p
        words = self.name.split()
        return "".join(w[0] for w in words if w and w[0].isalpha()).lower()

    @property
    def github(self) -> dict[str, Any]:
        """GitHub org/repo info (v0.4.0 ``github`` block, falls back to ``ecosystem``)."""
        return self.data.get("github") or self.data.get("ecosystem", {{}})

    @property
    def organization(self) -> str:
        return self.github.get("organization", "")

    @property
    def structure(self) -> StructureConfig:
        raw = self.data.get("structure", {{}})
        return StructureConfig.from_dict(raw) if isinstance(raw, dict) else StructureConfig()

    @property
    def services(self) -> dict[str, ServiceConfig]:
        raw = self.data.get("services", {{}})
        return {{name: ServiceConfig.from_dict(cfg) for name, cfg in raw.items() if isinstance(cfg, dict)}}

    @property
    def databases(self) -> dict[str, Any]:
        # v0.3.0: top-level databases block
        top = self.data.get("databases", {{}})
        if top:
            return top
        # v0.4.0: aggregate from per-service inline database dicts
        agg: dict[str, Any] = {{}}
        for svc_name, svc_raw in self.data.get("services", {{}}).items():
            if isinstance(svc_raw, dict) and isinstance(svc_raw.get("database"), dict):
                agg[svc_name] = svc_raw["database"]
        return agg

    @property
    def ci(self) -> dict[str, Any]:
        return self.data.get("ci", {{}})

    @property
    def environments(self) -> dict[str, EnvironmentConfig]:
        raw = self.ci.get("environments", {{}})
        if not raw:
            return {{
                "prod": EnvironmentConfig(branch="release"),
                "dev": EnvironmentConfig(branch="develop"),
                "test": EnvironmentConfig(branch="qa"),
            }}
        return {{name: EnvironmentConfig.from_dict(cfg) for name, cfg in raw.items() if isinstance(cfg, dict)}}

    def resolve_environment(self, branch: str) -> str | None:
        for env_name, env_cfg in self.environments.items():
            if env_cfg.branch == branch and env_cfg.enabled:
                return env_name
        return None
'''


def _gen_conventions(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Convention engine — resolves deployment profiles from service identity.

Pure functions, no I/O, no AWS calls.  Input is manifest data, output is
a fully-resolved DeploymentProfile.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from core.manifest_reader import (
    CdnConfig,
    DeployConfig,
    Manifest,
    SecretMapping,
    ServiceConfig,
    SidecarDeployConfig,
    SidecarHealthCheck,
    StructureConfig,
)


@dataclass(frozen=True)
class DeploymentProfile:
    """Fully-resolved deployment configuration for a single service."""
    name: str
    kind: str
    type: str
    role: str
    strategy: str
    dockerfile: str | None
    build_context: str
    build_command: str | None
    secrets: tuple[SecretMapping, ...]
    cdn: bool | CdnConfig | None
    depends_on: tuple[str, ...]
    sidecars: dict[str, SidecarDeployConfig]
    watch_paths: tuple[str, ...]
    database: str | None

    @property
    def is_deployable(self) -> bool:
        return self.strategy != "none"

    @property
    def needs_docker(self) -> bool:
        return self.strategy == "service"

    @property
    def needs_node(self) -> bool:
        return self.type in ("nextjs", "vite", "react", "vue", "angular")

    @property
    def needs_database_migration(self) -> bool:
        return self.database is not None

    @property
    def iac_key(self) -> str:
        """IaC-convention key: backends get -service, frontends get -frontend."""
        if self.kind == "backend":
            return f"{{self.name}}-service"
        elif self.kind == "frontend":
            return f"{{self.name}}-frontend"
        return self.name

    @property
    def has_sidecars(self) -> bool:
        return bool(self.sidecars)


STRATEGY_DEFAULTS: dict[tuple[str, str | None], str] = {{
    ("backend", "spring-boot"): "service",
    ("backend", "uvicorn"): "service",
    ("backend", "gunicorn"): "service",
    ("backend", "express"): "service",
    ("backend", "django"): "service",
    ("backend", "flask"): "service",
    ("backend", None): "service",
    ("frontend", "vite"): "static",
    ("frontend", "react"): "static",
    ("frontend", "vue"): "static",
    ("frontend", "angular"): "static",
    ("frontend", "nextjs"): "service",
    ("frontend", None): "service",
    ("package", None): "none",
}}

BUILD_CONTEXT_DEFAULTS: dict[tuple[str, str | None], str] = {{
    ("backend", "spring-boot"): ".",
    ("backend", "uvicorn"): "{{apps_dir}}/backend/{{name}}",
    ("backend", "gunicorn"): "{{apps_dir}}/backend/{{name}}",
    ("backend", "express"): ".",
    ("backend", None): "{{apps_dir}}/backend/{{name}}",
    ("frontend", "nextjs"): ".",
    ("frontend", None): "{{apps_dir}}/frontend/{{name}}",
}}


def resolve_profile(
    name: str,
    service: ServiceConfig,
    structure: StructureConfig,
    databases: dict[str, Any],
) -> DeploymentProfile:
    """Resolve a complete DeploymentProfile from service config + conventions."""
    kind = service.kind or "backend"
    type_ = service.type
    role = service.role or "other"
    deploy = service.deploy or DeployConfig()

    # Resolve database name — inline dict uses service name;
    # string reference to top-level databases block.
    if isinstance(service.database, dict):
        db = name  # Service name IS the logical DB name
    elif isinstance(service.database, str):
        db = service.database
    else:
        db = None

    # Strategy — deploy block > convention default
    _LEGACY = {{"ecs": "service", "s3-static": "static"}}
    raw = (
        (deploy.strategy if deploy else None)
        or STRATEGY_DEFAULTS.get(
            (kind, type_), STRATEGY_DEFAULTS.get((kind, None), "none")
        )
    )
    strategy = _LEGACY.get(raw, raw)

    dockerfile: str | None = None
    if strategy == "service":
        dockerfile = deploy.dockerfile or f"{{structure.apps_dir}}/{{kind}}/{{name}}/Dockerfile"

    ctx_template = BUILD_CONTEXT_DEFAULTS.get(
        (kind, type_), BUILD_CONTEXT_DEFAULTS.get((kind, None), f"{{structure.apps_dir}}/{{kind}}/{{name}}")
    )
    build_context = deploy.build_context or ctx_template.format(
        apps_dir=structure.apps_dir, kind=kind, name=name,
    )

    build_command: str | None = None
    if strategy == "static" and type_ in ("nextjs", "vite", "react", "vue", "angular"):
        build_command = deploy.build_command or "pnpm build"

    sidecars = dict(deploy.sidecars) if deploy.sidecars else {{}}

    if deploy.secrets:
        secrets = deploy.secrets
    else:
        secrets = _default_secrets(kind, type_, role, name, strategy, structure, dockerfile)

    if deploy.cdn is not None:
        cdn = deploy.cdn
    elif strategy == "static":
        cdn = True
    elif kind == "frontend" and strategy == "service":
        cdn = True
    else:
        cdn = False

    if deploy.depends_on:
        depends_on = deploy.depends_on
    else:
        deps: list[str] = ["iac"] if strategy != "none" else []
        if db and db in databases:
            deps.append(f"database:{{db}}")
        for sc_name in sidecars:
            deps.append(f"sidecar:{{sc_name}}")
        depends_on = tuple(deps)

    apps_dir = structure.apps_dir
    packages_dir = structure.packages_dir
    if kind == "backend":
        watch_paths = (f"^{{apps_dir}}/backend/{{name}}/",)
    elif kind == "frontend":
        watch_paths = (f"^{{apps_dir}}/frontend/{{name}}/", f"^{{packages_dir}}/")
    elif kind == "package":
        watch_paths = (f"^{{packages_dir}}/{{name}}/",)
    else:
        watch_paths = ()

    return DeploymentProfile(
        name=name, kind=kind, type=type_ or "other", role=role,
        strategy=strategy, dockerfile=dockerfile, build_context=build_context,
        build_command=build_command, secrets=secrets, cdn=cdn,
        depends_on=depends_on, sidecars=sidecars, watch_paths=watch_paths,
        database=db,
    )


def _default_secrets(
    kind: str, type_: str | None, role: str | None,
    name: str, strategy: str, structure: StructureConfig,
    dockerfile: str | None = None,
) -> tuple[SecretMapping, ...]:
    if strategy == "none":
        return ()
    apps_dir = structure.apps_dir
    secrets: list[SecretMapping] = []

    # Derive service folder from dockerfile path (handles mismatches like
    # service "microlith" with folder "platform-microlith"). Falls back to
    # service name if no dockerfile is specified.
    if dockerfile:
        from pathlib import PurePosixPath
        service_folder = PurePosixPath(dockerfile).parent.name
    else:
        service_folder = name

    if type_ == "spring-boot":
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/{{service}}-spring-properties",
            target=f"{{apps_dir}}/backend/{{service_folder}}/src/main/resources/application-{{{{env}}}}.yml",
            optional=True,
        ))
        if role == "auth":
            secrets.append(SecretMapping(
                source="{{prefix}}-{{env}}/efga-spring-properties",
                target=f"{{apps_dir}}/backend/{{service_folder}}/src/main/resources/efga-{{{{env}}}}.yml",
                optional=True,
            ))
    elif type_ in ("uvicorn", "gunicorn", "flask", "django"):
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/{{service}}-env",
            target=f"{{apps_dir}}/backend/{{service_folder}}/.env",
            optional=True,
        ))
    elif kind == "frontend" and strategy != "static":
        secrets.append(SecretMapping(
            source="{{prefix}}-{{env}}/{{service}}-env",
            target=f"{{apps_dir}}/frontend/{{service_folder}}/.env.production",
            optional=True,
        ))
    return tuple(secrets)


def resolve_all_profiles(manifest: Manifest) -> dict[str, DeploymentProfile]:
    """Resolve deployment profiles for all services in a manifest."""
    structure = manifest.structure
    databases = manifest.databases
    profiles: dict[str, DeploymentProfile] = {{}}
    for name, svc in manifest.services.items():
        profiles[name] = resolve_profile(name, svc, structure, databases)
    return profiles
'''


def _gen_secrets(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Secret fetching — downloads secrets from Secrets Manager.

Generic handler that processes SecretMapping objects.  No service-specific
``if`` branches.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from core.manifest_reader import SecretMapping

logger = logging.getLogger(__name__)


def fetch_and_write_secret(
    mapping: SecretMapping,
    secrets_client: Any,
    prefix: str,
    env: str,
    service: str,
) -> Path:
    """Fetch a single secret from Secrets Manager and write to target path.

    Supports interpolation of {{prefix}}, {{env}}, {{service}} in both
    source and target.
    """
    source = mapping.source.format(prefix=prefix, env=env, service=service)
    target = mapping.target.format(prefix=prefix, env=env, service=service)

    logger.info(f"📥 Fetching secret: {{source}}")
    response = secrets_client.get_secret_value(SecretId=source)
    content = response["SecretString"]

    if mapping.format == "extract-key" and mapping.extract_key:
        content = _extract_key(content, mapping.extract_key)
    elif mapping.format == "dotenv":
        pass  # Write as-is for dotenv format

    target_path = Path(target)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(content, encoding="utf-8")
    logger.info(f"✅ Secret written to: {{target_path}}")
    return target_path


def fetch_all_secrets(
    secrets: tuple[SecretMapping, ...],
    secrets_client: Any,
    prefix: str,
    env: str,
    service: str,
) -> list[Path]:
    """Fetch all secrets for a service."""
    paths: list[Path] = []
    for mapping in secrets:
        try:
            path = fetch_and_write_secret(mapping, secrets_client, prefix, env, service)
            paths.append(path)
        except Exception as e:
            if mapping.optional:
                source = mapping.source.format(prefix=prefix, env=env, service=service)
                logger.warning(f"⚠️ Optional secret not found: {{source}} — skipping")
            else:
                logger.error(f"❌ Failed to fetch secret {{mapping.source}}: {{e}}")
                raise
    return paths


def _extract_key(content: str, key: str) -> str:
    """Extract a specific key from JSON or dotenv secret content."""
    s = content.strip()
    try:
        parsed = json.loads(s)
        if isinstance(parsed, dict) and key in parsed:
            return str(parsed[key]).strip()
    except (json.JSONDecodeError, ValueError):
        pass
    for line in s.splitlines():
        line = line.strip()
        if "=" in line:
            k, v = line.split("=", 1)
            if k.strip() == key:
                return v.strip().strip("\\"\\'")
    return s
'''


def _gen_ecs_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""ECS Fargate deployment engine.

Builds Docker images, pushes to ECR, registers task definitions, and updates
ECS services.  Completely generic — driven entirely by DeploymentProfile.
"""

from __future__ import annotations

import base64
import json
import logging
import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

from core.conventions import DeploymentProfile
from core.secrets import fetch_all_secrets

logger = logging.getLogger(__name__)


class EcsEngine:
    """Generic ECS Fargate deployment engine."""

    def __init__(self, profile: DeploymentProfile, environment: str, prefix: str, session: Any):
        self.profile = profile
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.iac_outputs = self._load_iac_outputs()
        self._manifest = self._load_manifest()

    def _load_manifest(self) -> dict[str, Any]:
        """Load foundry.json manifest for service configuration."""
        manifest_path = Path("foundry.json")
        if manifest_path.exists():
            return json.loads(manifest_path.read_text(encoding="utf-8"))
        return {{}}

    def _get_database_schema(self, service_name: str) -> str | None:
        """Get the database schema for a service from the manifest."""
        services = self._manifest.get("services", {{}})
        svc_config = services.get(service_name, {{}})
        db_config = svc_config.get("database")
        if isinstance(db_config, dict):
            return db_config.get("schema")
        return None

    def build_and_push(self) -> str:
        """Build Docker image and push to ECR.  Returns the full image URI."""
        logger.info(f"🏗️ Building and pushing {{self.profile.name}}...")

        # 1. Fetch secrets
        secrets_client = self.session.client("secretsmanager")
        fetch_all_secrets(
            self.profile.secrets, secrets_client,
            self.prefix, self.env, self.profile.name,
        )

        # Ensure target files exist for optional secrets that were skipped.
        # Dockerfiles may COPY these files unconditionally.
        for mapping in self.profile.secrets:
            if mapping.optional:
                target = Path(mapping.target.format(
                    prefix=self.prefix, env=self.env, service=self.profile.name,
                ))
                if not target.exists():
                    target.parent.mkdir(parents=True, exist_ok=True)
                    target.touch()
                    logger.info(f"Created empty fallback: {{target}}")

        # 2. Get ECR repo (IaC names: backends get -service, frontends get -frontend)
        ecr_client = self.session.client("ecr")
        repo_name = f"{{self.prefix}}-{{self.env}}-{{self.profile.iac_key}}"
        repo_uri = self._get_ecr_repo_uri(ecr_client, repo_name)

        # 3. ECR login
        self._ecr_login(ecr_client)

        # 4. Build and push
        git_sha = self._get_git_sha()
        image_uri = f"{{repo_uri}}:{{git_sha}}"

        env = os.environ.copy()
        env["DOCKER_BUILDKIT"] = "1"

        build_args = [
            "docker", "buildx", "build",
            "--progress=plain",
            "-f", str(self.profile.dockerfile),
            "-t", image_uri,
            "--push",
        ]
        # GHA cache for BuildKit layers (Maven .m2, npm, etc.) — scoped per
        # service to prevent cross-service eviction. Requires the Actions
        # runtime env (exported by crazy-max/ghaction-github-runtime in the
        # generated pipeline); skipped on local runs where it would error.
        if os.environ.get("ACTIONS_RUNTIME_TOKEN"):
            build_args.extend([
                "--cache-from", f"type=gha,scope={{self.profile.name}}",
                "--cache-to", f"type=gha,scope={{self.profile.name}},mode=max",
            ])
        # Registry cache for Docker layers (fallback if GHA cache misses).
        # image-manifest/oci flags are required for ECR to accept a cache
        # manifest (plain buildkit cacheconfig media types are rejected).
        build_args.extend([
            "--cache-from", f"type=registry,ref={{repo_uri}}:buildcache",
            "--cache-to", (f"type=registry,ref={{repo_uri}}:buildcache,"
                           "mode=max,image-manifest=true,oci-mediatypes=true"),
        ])

        # Pass GITHUB_TOKEN as Docker secret for GitHub Packages auth
        if os.environ.get("GITHUB_TOKEN"):
            build_args.extend(["--secret", "id=GITHUB_TOKEN,env=GITHUB_TOKEN"])

        build_args.append(str(self.profile.build_context))

        logger.info(f"Running: {{' '.join(build_args)}}")
        subprocess.run(build_args, check=True, env=env)
        logger.info(f"✅ Image pushed: {{image_uri}}")
        return image_uri

    def deploy(self, image_uri: str | None = None) -> None:
        """Update ECS service with a new task definition."""
        logger.info(f"🚀 Deploying {{self.profile.name}} to ECS...")

        if image_uri is None:
            image_uri = self._calculate_image_uri()

        ecs_client = self.session.client("ecs")
        cluster = f"{{self.prefix}}-{{self.env}}-cluster"

        task_def = self._build_task_definition(image_uri)
        result = ecs_client.register_task_definition(**task_def)
        task_def_arn = result["taskDefinition"]["taskDefinitionArn"]

        iac_key = self.profile.iac_key
        desired_count = self._get_output(f"ecs_services.{{iac_key}}.compute_config.desired_count")
        if desired_count is None:
            raise ValueError(f"Missing IaC output: ecs_services.{{iac_key}}.compute_config.desired_count")

        ecs_client.update_service(
            cluster=cluster,
            service=iac_key,
            taskDefinition=task_def_arn,
            desiredCount=desired_count,
            forceNewDeployment=self.profile.has_sidecars,
        )

        self._wait_for_deployment(ecs_client, cluster, iac_key)
        logger.info(f"✅ {{self.profile.name}} deployed successfully")

    # ── Internal helpers ──────────────────────────────────────────────

    def _build_task_definition(self, image_uri: str) -> dict[str, Any]:
        svc = self.profile.name
        iac_key = self.profile.iac_key
        cpu = self._require_output(f"ecs_services.{{iac_key}}.compute_config.cpu")
        memory = self._require_output(f"ecs_services.{{iac_key}}.compute_config.memory")
        exec_role = self._require_output(f"ecs_services.{{iac_key}}.execution_role_arn")
        task_role = self._require_output(f"ecs_services.{{iac_key}}.task_role_arn")
        log_group = self._require_output(f"ecs_services.{{iac_key}}.log_group_name")
        container_config = self._require_output(f"ecs_services.{{iac_key}}.container_config")
        container_port = container_config["port"]
        aws_region = self.session.region_name

        env_vars = [
            {{"name": "ENV", "value": self.env}},
            {{"name": "PLATFORM_PREFIX", "value": self.prefix}},
        ]
        if self.profile.type == "spring-boot":
            env_vars.append({{"name": "SPRING_PROFILES_ACTIVE", "value": self.env}})
        tf_env = container_config.get("environment")
        if isinstance(tf_env, dict):
            env_vars.extend({{"name": k, "value": v}} for k, v in tf_env.items())
        elif isinstance(tf_env, list):
            env_vars.extend(tf_env)

        # Use iac_key for container name to match IaC target group configuration
        main_container = {{
            "name": iac_key,
            "image": image_uri,
            "essential": True,
            "portMappings": [{{"containerPort": container_port, "protocol": "tcp"}}],
            "environment": env_vars,
            "logConfiguration": {{
                "logDriver": "awslogs",
                "options": {{
                    "awslogs-group": log_group,
                    "awslogs-region": aws_region,
                    "awslogs-stream-prefix": "ecs",
                }},
            }},
        }}

        containers = [main_container]

        # Add sidecars from profile (e.g., OpenFGA)
        for sc_name, sc_config in self.profile.sidecars.items():
            sidecar = {{
                "name": sc_name,
                "image": sc_config.image,
                "essential": sc_config.essential,
                "cpu": sc_config.cpu,
                "memory": sc_config.memory,
                "memoryReservation": sc_config.cpu,
                "logConfiguration": {{
                    "logDriver": "awslogs",
                    "options": {{
                        "awslogs-group": log_group,
                        "awslogs-region": aws_region,
                        "awslogs-stream-prefix": sc_name,
                    }},
                }},
            }}
            if sc_config.port:
                sidecar["portMappings"] = [{{"containerPort": sc_config.port, "protocol": "tcp"}}]
            if sc_config.command:
                sidecar["command"] = list(sc_config.command)
            if sc_config.health_check:
                sidecar["healthCheck"] = {{
                    "command": ["CMD-SHELL", sc_config.health_check.command],
                    "interval": sc_config.health_check.interval,
                    "timeout": sc_config.health_check.timeout,
                    "retries": sc_config.health_check.retries,
                    "startPeriod": sc_config.health_check.start_period,
                }}
            if sc_config.environment:
                sc_env = dict(sc_config.environment)
                # Resolve placeholder datastore URIs from database credentials
                if sc_env.get("OPENFGA_DATASTORE_URI", "").startswith("placeholder://"):
                    db_schema = self._get_database_schema(svc)
                    sc_env["OPENFGA_DATASTORE_URI"] = self._resolve_datastore_uri(svc, db_schema)
                sidecar["environment"] = [{{"name": k, "value": v}} for k, v in sc_env.items()]
            containers.append(sidecar)

        task_def: dict[str, Any] = {{
            "family": f"{{self.prefix}}-{{self.env}}-{{iac_key}}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": str(cpu),
            "memory": str(memory),
            "executionRoleArn": exec_role,
            "taskRoleArn": task_role,
            "containerDefinitions": containers,
        }}

        # EFS volumes
        efs_info = self._get_output(f"ecs_services.{{iac_key}}.efs")
        if efs_info and isinstance(efs_info, dict):
            fs_id = efs_info.get("file_system_id")
            if fs_id:
                vol_name = f"{{svc}}-efs"
                vol = {{
                    "name": vol_name,
                    "efsVolumeConfiguration": {{
                        "fileSystemId": fs_id,
                        "rootDirectory": efs_info.get("root_directory", "/"),
                        "transitEncryption": "ENABLED",
                    }},
                }}
                ap_id = efs_info.get("access_point_id") or efs_info.get("access_point")
                if ap_id:
                    vol["efsVolumeConfiguration"]["authorizationConfig"] = {{
                        "accessPointId": ap_id, "iam": "ENABLED",
                    }}
                task_def["volumes"] = [vol]
                mount_path = efs_info.get("mount_path", f"/mnt/{{svc}}")
                main_container["mountPoints"] = [{{
                    "sourceVolume": vol_name,
                    "containerPath": mount_path,
                    "readOnly": False,
                }}]
                env_vars.append({{"name": "EFS_MOUNT_PATH", "value": mount_path}})

        return task_def

    def _calculate_image_uri(self) -> str:
        ecr_client = self.session.client("ecr")
        repo_name = f"{{self.prefix}}-{{self.env}}-{{self.profile.iac_key}}"
        repo_uri = self._get_ecr_repo_uri(ecr_client, repo_name)
        git_sha = self._get_git_sha()
        return f"{{repo_uri}}:{{git_sha}}"

    def _get_ecr_repo_uri(self, ecr_client: Any, repo_name: str) -> str:
        response = ecr_client.describe_repositories(repositoryNames=[repo_name])
        return response["repositories"][0]["repositoryUri"]

    def _resolve_datastore_uri(self, service_name: str, schema: str | None = None) -> str:
        """Resolve OpenFGA datastore URI from database credentials secret.

        Args:
            service_name: The service name to fetch credentials for.
            schema: Optional PostgreSQL schema name to set as search_path.
        """
        from urllib.parse import quote_plus
        secret_id = f"{{self.prefix}}-{{self.env}}/{{service_name}}/credentials"
        sm_client = self.session.client("secretsmanager")
        try:
            resp = sm_client.get_secret_value(SecretId=secret_id)
            creds = json.loads(resp["SecretString"])
            # Build postgres URI: postgres://user:pass@host:port/dbname?sslmode=require
            user = quote_plus(creds["username"])
            password = quote_plus(creds["password"])
            host = creds["host"]
            port = creds.get("port", 5432)
            dbname = creds["dbname"]
            uri = f"postgres://{{user}}:{{password}}@{{host}}:{{port}}/{{dbname}}?sslmode=require"
            if schema:
                uri += f"&search_path={{schema}}"
            return uri
        except Exception as e:
            logger.warning(f"⚠️ Could not resolve datastore URI from {{secret_id}}: {{e}}")
            raise ValueError(f"Failed to resolve datastore URI for {{service_name}}: {{e}}")

    def _ecr_login(self, ecr_client: Any) -> None:
        token_resp = ecr_client.get_authorization_token()
        token = token_resp["authorizationData"][0]["authorizationToken"]
        endpoint = token_resp["authorizationData"][0]["proxyEndpoint"]
        username, password = base64.b64decode(token).decode().split(":")
        proc = subprocess.run(
            ["docker", "login", "--username", username, "--password-stdin", endpoint],
            input=password, text=True, capture_output=True, check=True,
        )

    def _wait_for_deployment(self, ecs_client: Any, cluster: str, service: str, timeout: int = 600) -> None:
        logger.info("⏳ Waiting for deployment to stabilize...")
        start = time.time()
        while time.time() - start < timeout:
            resp = ecs_client.describe_services(cluster=cluster, services=[service])
            svc = resp["services"][0]
            primary = next((d for d in svc["deployments"] if d["status"] == "PRIMARY"), None)
            if primary and primary["runningCount"] == primary["desiredCount"]:
                return
            time.sleep(30)
        raise TimeoutError(f"Deployment of {{service}} did not stabilize in {{timeout}}s")

    def _load_iac_outputs(self) -> dict[str, Any]:
        path = Path("iac-outputs/iac-outputs.json")
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
        return {{}}

    def _get_output(self, dotpath: str, default: Any = None) -> Any:
        value = self.iac_outputs
        for key in dotpath.split("."):
            if isinstance(value, dict) and key in value:
                v = value[key]
                if isinstance(v, dict) and "value" in v and "type" in v:
                    value = v["value"]
                else:
                    value = v
            else:
                return default
        return value

    def _require_output(self, dotpath: str) -> Any:
        val = self._get_output(dotpath)
        if val is None:
            raise ValueError(f"❌ Missing required IaC output: {{dotpath}}")
        return val

    @staticmethod
    def _get_git_sha() -> str:
        try:
            return subprocess.run(
                ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True,
            ).stdout.strip()
        except subprocess.CalledProcessError:
            return "unknown"
'''


def _gen_s3_static_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""S3 + CloudFront static site deployment engine.

Builds the static site, syncs to S3, and invalidates CloudFront.
Completely generic — driven by DeploymentProfile.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import time
from pathlib import Path
from typing import Any

from core.conventions import DeploymentProfile
from core.secrets import fetch_all_secrets

logger = logging.getLogger(__name__)


class S3StaticEngine:
    """Generic S3 + CloudFront static site deployment engine."""

    def __init__(self, profile: DeploymentProfile, environment: str, prefix: str, session: Any):
        self.profile = profile
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.iac_outputs = self._load_iac_outputs()

    def build_and_deploy(self) -> None:
        """Build the static site, sync to S3, and invalidate CDN."""
        logger.info(f"🏗️ Building and deploying {{self.profile.name}} (s3-static)...")

        # 1. Fetch secrets
        secrets_client = self.session.client("secretsmanager")
        fetch_all_secrets(
            self.profile.secrets, secrets_client,
            self.prefix, self.env, self.profile.name,
        )

        # 2. Install dependencies
        logger.info("📦 Installing dependencies...")
        subprocess.run(["pnpm", "install", "--frozen-lockfile"], check=True)

        # 3. Build
        logger.info(f"🔨 Building {{self.profile.name}}...")
        build_dir = Path(self.profile.build_context)
        subprocess.run(
            ["pnpm", "--filter", self.profile.name, "build"],
            check=True, cwd=build_dir if build_dir != Path(".") else None,
        )

        # 4. Find output directory
        output_dir = self._find_output_dir()

        # 5. Sync to S3 (bucket name from IaC outputs or convention)
        bucket = self._get_bucket_name()
        self._sync_to_s3(output_dir, bucket)

        # 6. Invalidate CDN
        if self.profile.cdn:
            self._invalidate_cdn()

        logger.info(f"✅ {{self.profile.name}} deployed to S3")

    def _find_output_dir(self) -> Path:
        """Find the build output directory for the static site."""
        structure = Path("foundry.json")  # We're in repo root
        manifest_data = json.loads(structure.read_text(encoding="utf-8"))
        apps_dir = manifest_data.get("structure", {{}}).get("appsDir", "apps")
        # Next.js static export → out/, Vite → dist/
        for candidate in ["out", "dist", "build"]:
            p = Path(apps_dir) / "frontend" / self.profile.name / candidate
            if p.exists():
                return p
        raise FileNotFoundError(f"Could not find build output for {{self.profile.name}}")

    def _sync_to_s3(self, output_dir: Path, bucket: str) -> None:
        logger.info(f"📤 Syncing {{output_dir}} → s3://{{bucket}}/")
        s3_client = self.session.client("s3")
        for file_path in output_dir.rglob("*"):
            if file_path.is_file():
                key = str(file_path.relative_to(output_dir)).replace("\\\\", "/")
                content_type = self._guess_content_type(key)
                s3_client.upload_file(
                    str(file_path), bucket, key,
                    ExtraArgs={{"ContentType": content_type}},
                )
        logger.info(f"✅ Synced to s3://{{bucket}}/")

    def _get_bucket_name(self) -> str:
        """Get S3 bucket name from IaC outputs or convention."""
        iac_key = self.profile.iac_key
        bucket = self._get_output(f"static_sites.{{iac_key}}.bucket_name")
        if bucket:
            return bucket
        return f"{{self.prefix}}-{{self.env}}-{{iac_key}}"

    def _invalidate_cdn(self) -> None:
        dist_id = self._get_distribution_id()
        if not dist_id:
            logger.warning("⚠️ No CloudFront distribution ID found — skipping invalidation")
            return
        cf_client = self.session.client("cloudfront")
        cf_client.create_invalidation(
            DistributionId=dist_id,
            InvalidationBatch={{
                "Paths": {{"Quantity": 1, "Items": ["/*"]}},
                "CallerReference": f"deploy-{{int(time.time())}}",
            }},
        )
        logger.info(f"✅ CloudFront invalidation created for {{dist_id}}")

    def _get_distribution_id(self) -> str | None:
        iac_key = self.profile.iac_key
        # Try static_sites output path
        dist_id = self._get_output(
            f"static_sites.{{iac_key}}.cloudfront_distribution_id"
        )
        if dist_id:
            return dist_id
        # Fallback: try legacy output paths
        dist_id = self._get_output(
            f"cloudfront_distributions.{{self.profile.name}}.distribution_id"
        )
        return dist_id

    def _load_iac_outputs(self) -> dict[str, Any]:
        path = Path("iac-outputs/iac-outputs.json")
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
        return {{}}

    def _get_output(self, dotpath: str, default: Any = None) -> Any:
        value = self.iac_outputs
        for key in dotpath.split("."):
            if isinstance(value, dict) and key in value:
                v = value[key]
                if isinstance(v, dict) and "value" in v and "type" in v:
                    value = v["value"]
                else:
                    value = v
            else:
                return default
        return value

    @staticmethod
    def _guess_content_type(key: str) -> str:
        ext = key.rsplit(".", 1)[-1].lower() if "." in key else ""
        return {{
            "html": "text/html",
            "css": "text/css",
            "js": "application/javascript",
            "json": "application/json",
            "png": "image/png",
            "jpg": "image/jpeg",
            "jpeg": "image/jpeg",
            "svg": "image/svg+xml",
            "ico": "image/x-icon",
            "woff2": "font/woff2",
            "woff": "font/woff",
            "ttf": "font/ttf",
            "txt": "text/plain",
            "xml": "application/xml",
            "webp": "image/webp",
        }}.get(ext, "application/octet-stream")
'''


def _gen_tfvars_generator(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Pipeline tfvars generator \u2014 fetches IAC config and writes .auto.tfvars.json.

Mirrors the logic from ``foundry generate tfvars`` but runs in CI pipelines
without requiring the Foundry CLI.  Reads foundry.json for service identity
and naming, fetches infrastructure config from Secrets Manager, resolves
template variables and cross-references, and writes JSON tfvars.

Data flow:
  foundry.json (service names, kinds, strategies, prefix)
  + Secrets Manager ({{prefix}}-{{env}}/iac/config)
  + STS (account_id) + Route 53 (hosted_zone_id)
  -> ci/iac/{{env}}/{{env}}.auto.tfvars.json
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# -- Naming Conventions ---------------------------------------------------


def _iac_service_name(manifest_name: str, kind: str) -> str:
    """Derive the IaC key for an ECS service from manifest name + kind.

    Backends get ``-service`` suffix, frontends get ``-frontend``.
    """
    if kind == "backend":
        return f"{{manifest_name}}-service"
    if kind == "frontend":
        return f"{{manifest_name}}-frontend"
    return manifest_name


def _iac_static_site_name(manifest_name: str) -> str:
    """Derive the IaC key for a static site from manifest name."""
    if manifest_name.endswith("-frontend"):
        return manifest_name
    return f"{{manifest_name}}-frontend"


# -- Template & Cross-Reference Resolution --------------------------------


def _resolve_templates(value: Any, variables: dict[str, str]) -> Any:
    """Walk a data structure and resolve ``{{placeholder}}`` templates."""
    if isinstance(value, str):
        try:
            return value.format_map(variables)
        except (KeyError, ValueError):
            return value
    if isinstance(value, dict):
        return {{k: _resolve_templates(v, variables) for k, v in value.items()}}
    if isinstance(value, (list, tuple)):
        return [_resolve_templates(v, variables) for v in value]
    return value


def _resolve_refs(value: Any, name_map: dict[str, str]) -> Any:
    """Walk a data structure and resolve ``service:XXX`` cross-references."""
    if isinstance(value, str):
        for manifest_name, iac_name in name_map.items():
            value = value.replace(
                f"service:{{manifest_name}}", f"service:{{iac_name}}"
            )
        return value
    if isinstance(value, dict):
        return {{k: _resolve_refs(v, name_map) for k, v in value.items()}}
    if isinstance(value, (list, tuple)):
        return [_resolve_refs(v, name_map) for v in value]
    return value


# -- AWS Helpers ----------------------------------------------------------


def _fetch_iac_config(session: Any, secret_id: str) -> dict[str, Any]:
    """Fetch the IAC config JSON from Secrets Manager.

    Returns an empty dict if the secret cannot be loaded, allowing
    downstream code to fall back to foundry.json defaults.
    """
    try:
        client = session.client("secretsmanager")
        logger.info("Fetching IAC config from secret: %s", secret_id)
        response = client.get_secret_value(SecretId=secret_id)
        secret_str = response["SecretString"]
        # Strip UTF-8 BOM if present (can sneak in from editors/copy-paste)
        if secret_str.startswith("\\xef\\xbb\\xbf"):
            secret_str = secret_str[3:]
        config = json.loads(secret_str)
        logger.info(
            "Loaded IAC config: %d top-level keys, %d service configs",
            len(config),
            len(config.get("services", {{}})),
        )
        return config
    except client.exceptions.ResourceNotFoundException:
        logger.warning("IAC config secret '%s' not found — using foundry.json defaults", secret_id)
        return {{}}
    except json.JSONDecodeError as exc:
        logger.warning("IAC config secret '%s' is not valid JSON: %s — using foundry.json defaults", secret_id, exc)
        return {{}}
    except Exception as exc:
        logger.warning("Could not fetch IAC config from '%s': %s — using foundry.json defaults", secret_id, exc)
        return {{}}


def _resolve_account_id(session: Any) -> str:
    """Get the AWS account ID from STS."""
    try:
        sts = session.client("sts")
        identity = sts.get_caller_identity()
        account_id = identity["Account"]
        logger.info("Resolved account_id from STS: %s", account_id)
        return account_id
    except Exception as exc:
        logger.warning("Could not resolve account_id: %s", exc)
        return "000000000000"


def _resolve_hosted_zone_id(session: Any, domain_name: str) -> str:
    """Resolve the Route 53 hosted zone ID for a domain."""
    if not domain_name:
        return ""
    try:
        r53 = session.client("route53")
        response = r53.list_hosted_zones_by_name(DNSName=domain_name, MaxItems="1")
        zones = response.get("HostedZones", [])
        for zone in zones:
            zone_name = zone["Name"].rstrip(".")
            if zone_name == domain_name.rstrip("."):
                zone_id = zone["Id"].split("/")[-1]
                logger.info(
                    "Resolved hosted_zone_id for %s: %s", domain_name, zone_id
                )
                return zone_id
        logger.warning("No hosted zone found for domain: %s", domain_name)
    except Exception as exc:
        logger.warning("Could not resolve hosted_zone_id for %s: %s", domain_name, exc)
    return ""


# -- Port Derivation from Manifest ----------------------------------------


def _inject_manifest_ports(
    svc_iac: dict[str, Any],
    manifest_service: dict[str, Any],
) -> dict[str, Any]:
    """Inject container_port and health_check_port from manifest run config.

    Ports defined in ``foundry.json`` under ``services.{{name}}.run`` are used
    as defaults for IAC configuration. This allows committing port config to
    the repository rather than duplicating it in Secrets Manager.

    Priority: IAC secret values > manifest ``run`` config > hardcoded defaults.
    """
    result = dict(svc_iac)  # shallow copy
    run_cfg = manifest_service.get("run", {{}})

    # container_port
    manifest_port = run_cfg.get("port")
    if manifest_port and "container_port" not in result:
        result["container_port"] = manifest_port
        logger.debug("Derived container_port=%d from manifest run.port", manifest_port)

    # health_check_port (in alb block)
    actuator_port = run_cfg.get("actuatorPort")
    if actuator_port:
        alb = result.get("alb", {{}})
        if isinstance(alb, dict) and "health_check_port" not in alb:
            result["alb"] = {{**alb, "health_check_port": actuator_port}}
            logger.debug("Derived alb.health_check_port=%d from manifest run.actuatorPort", actuator_port)

    # security_group ingress port alignment
    container_port = result.get("container_port")
    health_port = result.get("alb", {{}}).get("health_check_port") if isinstance(result.get("alb"), dict) else None

    if container_port or health_port:
        sg = result.get("security_group", {{}})
        if isinstance(sg, dict) and "ingress" in sg:
            updated_rules = []
            for rule in sg.get("ingress", []):
                if not isinstance(rule, dict):
                    updated_rules.append(rule)
                    continue
                rule = dict(rule)
                if health_port and rule.get("description", "").lower().startswith("health check"):
                    if rule.get("from_port") in (9000, 9090, 9091):
                        rule["from_port"] = health_port
                        rule["to_port"] = health_port
                elif container_port and "health" not in rule.get("description", "").lower():
                    if rule.get("from_port") in (8080, 8081, 8090, 8091):
                        rule["from_port"] = container_port
                        rule["to_port"] = container_port
                updated_rules.append(rule)
            result["security_group"] = {{**sg, "ingress": updated_rules}}

    return result


def _inject_manifest_compute(
    svc_iac: dict[str, Any],
    manifest_service: dict[str, Any],
) -> dict[str, Any]:
    """Inject cpu and memory from manifest deploy.compute config.

    Compute resources defined in ``foundry.json`` under
    ``services.{{name}}.deploy.compute`` are used as defaults for IAC
    configuration. This allows committing resource sizing to the repository
    rather than duplicating it in Secrets Manager.

    Priority: IAC secret values > manifest ``deploy.compute`` > hardcoded defaults.
    """
    result = dict(svc_iac)  # shallow copy
    deploy_cfg = manifest_service.get("deploy", {{}})
    compute = deploy_cfg.get("compute", {{}})

    if not compute:
        return result

    # cpu
    manifest_cpu = compute.get("cpu")
    if manifest_cpu and "cpu" not in result:
        result["cpu"] = manifest_cpu
        logger.debug("Derived cpu=%d from manifest deploy.compute.cpu", manifest_cpu)

    # memory
    manifest_memory = compute.get("memory")
    if manifest_memory and "memory" not in result:
        result["memory"] = manifest_memory
        logger.debug("Derived memory=%d from manifest deploy.compute.memory", manifest_memory)

    return result


# -- Main Generator -------------------------------------------------------


def generate_tfvars_json(
    manifest: Any,
    env_name: str,
    session: Any,
    prefix: str,
) -> dict[str, Any]:
    """Generate the complete tfvars dict from manifest + Secrets Manager.

    Args:
        manifest: A loaded ``Manifest`` from manifest_reader.
        env_name: Target environment name (e.g., ``prod``).
        session: A boto3 Session.
        prefix: Platform prefix (e.g., ``acp``).

    Returns:
        Dict ready to be serialized as JSON and written to .auto.tfvars.json.
    """
    from core.conventions import resolve_all_profiles

    name_prefix = f"{{prefix}}-{{env_name}}"

    # -- Fetch IAC config from Secrets Manager ----------------------------
    secret_id = f"{{name_prefix}}/iac/config"
    iac_config = _fetch_iac_config(session, secret_id)
    region = iac_config.get("region", "us-east-1")

    # -- Resolve AWS identity ---------------------------------------------
    account_id = _resolve_account_id(session)

    domain_cfg: dict[str, Any] = iac_config.get("domain", {{}})
    hosted_zone_id = domain_cfg.get("hosted_zone_id", "")
    if not hosted_zone_id:
        hosted_zone_id = _resolve_hosted_zone_id(
            session, domain_cfg.get("name", "")
        )

    # -- Resolve deployment profiles --------------------------------------
    profiles = resolve_all_profiles(manifest)

    # Build naming map (manifest_name -> iac_name)
    name_map: dict[str, str] = {{}}
    for manifest_name, profile in profiles.items():
        if not profile.is_deployable:
            continue
        if profile.strategy == "static":
            name_map[manifest_name] = _iac_static_site_name(manifest_name)
        else:
            name_map[manifest_name] = _iac_service_name(
                manifest_name, profile.kind
            )

    # Global template variables
    global_vars: dict[str, str] = {{
        "prefix": prefix,
        "env": env_name,
        "name_prefix": name_prefix,
        "account_id": account_id,
        "region": region,
    }}

    # -- Platform block ---------------------------------------------------
    emp_ip_whitelist = iac_config.get("emp_ip_whitelist", [])
    platform_tags = {{**iac_config.get("tags", {{}}), "Environment": env_name}}
    platform_block: dict[str, Any] = {{
        "name": manifest.name or "Platform",
        "prefix": prefix,
        "environment": env_name,
        "region": region,
        "account_id": account_id,
        "emp_ip_whitelist": emp_ip_whitelist,
        "tags": platform_tags,
    }}

    # -- Services from secret config --------------------------------------
    secret_services: dict[str, Any] = iac_config.get("services", {{}})
    # Use raw service dicts from manifest.data, not ServiceConfig objects
    raw_services: dict[str, Any] = manifest.data.get("services", {{}}) if hasattr(manifest, "data") else {{}}

    # -- ECS services -----------------------------------------------------
    ecs_services: dict[str, dict[str, Any]] = {{}}
    for manifest_name, profile in sorted(profiles.items()):
        if not profile.is_deployable or profile.strategy == "static":
            continue

        svc_iac: dict[str, Any] = secret_services.get(manifest_name, {{}})
        if not svc_iac:
            logger.warning(
                "Service '%s' has no IAC config in secret \u2014 skipping",
                manifest_name,
            )
            continue

        # Inject ports from manifest run config (avoids duplicating in secret)
        manifest_svc = raw_services.get(manifest_name, {{}})
        svc_iac = _inject_manifest_ports(svc_iac, manifest_svc)

        # Inject compute resources from manifest deploy.compute
        svc_iac = _inject_manifest_compute(svc_iac, manifest_svc)

        iac_key = _iac_service_name(manifest_name, profile.kind)
        svc_vars: dict[str, str] = {{
            **global_vars,
            "iac_name": iac_key,
            "manifest_name": manifest_name,
        }}
        resolved = _resolve_templates(svc_iac, svc_vars)
        resolved = _resolve_refs(resolved, name_map)
        ecs_services[iac_key] = resolved

    # -- Static sites -----------------------------------------------------
    static_sites: dict[str, dict[str, Any]] = {{}}
    for manifest_name, profile in sorted(profiles.items()):
        if profile.strategy != "static":
            continue

        site_iac: dict[str, Any] = secret_services.get(manifest_name, {{}})
        if not site_iac:
            logger.warning(
                "Static site '%s' has no IAC config in secret \u2014 skipping",
                manifest_name,
            )
            continue

        iac_key = _iac_static_site_name(manifest_name)
        svc_vars: dict[str, str] = {{
            **global_vars,
            "iac_name": iac_key,
            "manifest_name": manifest_name,
        }}
        resolved = _resolve_templates(site_iac, svc_vars)
        static_sites[iac_key] = resolved

    # -- Assemble output --------------------------------------------------
    tfvars: dict[str, Any] = {{
        "platform": platform_block,
    }}

    # SES
    ses_arn = iac_config.get("ses_identity_arn")
    if ses_arn:
        tfvars["ses_identity_arn"] = _resolve_templates(ses_arn, global_vars)

    # Domain
    domain = iac_config.get("domain")
    if domain:
        domain = dict(domain)
        if hosted_zone_id:
            domain["hosted_zone_id"] = hosted_zone_id
        tfvars["domain"] = _resolve_templates(domain, global_vars)

    # Services
    if ecs_services:
        tfvars["services"] = ecs_services

    # Bastion
    bastion = iac_config.get("bastion")
    if bastion:
        tfvars["bastion"] = bastion

    # Static sites
    if static_sites:
        tfvars["static_sites"] = static_sites

    # Lambda functions
    lambda_fns = iac_config.get("lambda_functions")
    if lambda_fns:
        resolved_lambdas = _resolve_templates(lambda_fns, global_vars)
        resolved_lambdas = _resolve_refs(resolved_lambdas, name_map)
        tfvars["lambda_functions"] = resolved_lambdas

    # EventBridge rules
    eb_rules = iac_config.get("eventbridge_rules")
    if eb_rules:
        resolved_eb = _resolve_templates(eb_rules, global_vars)
        resolved_eb = _resolve_refs(resolved_eb, name_map)
        tfvars["eventbridge_rules"] = resolved_eb

    return tfvars


def write_tfvars_json(
    manifest: Any,
    env_name: str,
    session: Any,
    prefix: str,
    output_dir: Path,
) -> Path:
    """Generate tfvars and write to {{env}}.auto.tfvars.json.

    Args:
        manifest: A loaded ``Manifest`` from manifest_reader.
        env_name: Target environment name (e.g., ``prod``).
        session: A boto3 Session.
        prefix: Platform prefix (e.g., ``acp``).
        output_dir: The IaC working directory (e.g., ``ci/iac/prod``).

    Returns:
        Path to the written .auto.tfvars.json file.
    """
    tfvars = generate_tfvars_json(manifest, env_name, session, prefix)

    output_path = output_dir / f"{{env_name}}.auto.tfvars.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(tfvars, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    logger.info("Wrote tfvars to %s (%d bytes)", output_path, output_path.stat().st_size)
    return output_path
'''


def _gen_iac_engine(manifest: ProjectManifest, header: str) -> str:
    iac = manifest.data.get("ci", {}).get("iac", "opentofu")
    binary = "tofu" if iac == "opentofu" else "terraform"
    iac_dir = manifest.data.get("ci", {}).get("iacDir", "ci/iac")

    return f'''{header}
"""IaC engine — runs OpenTofu/Terraform plan and apply.

Reads the IaC directory from the manifest and runs the appropriate binary.
Automatically generates .auto.tfvars.json from Secrets Manager before planning.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

IAC_BINARY = "{binary}"
IAC_DIR = "{iac_dir}"


class IacEngine:
    """Runs IaC (OpenTofu/Terraform) operations."""

    def __init__(self, environment: str, prefix: str, session: Any):
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.work_dir = Path(IAC_DIR) / self.env

    def _generate_tfvars(self) -> None:
        """Generate .auto.tfvars.json from Secrets Manager config.

        Fetches infrastructure configuration from the IAC config secret
        ({{prefix}}-{{env}}/iac/config), resolves naming conventions and
        template variables, and writes {{env}}.auto.tfvars.json into the
        IaC working directory so that OpenTofu/Terraform auto-loads it.
        """
        from core.manifest_reader import Manifest
        from core.tfvars_generator import write_tfvars_json

        logger.info("📝 Generating tfvars from Secrets Manager...")
        manifest = Manifest.load()
        tfvars_path = write_tfvars_json(
            manifest, self.env, self.session, self.prefix, self.work_dir,
        )
        logger.info(f"✅ Generated {{tfvars_path}}")

    def plan(self) -> None:
        """Run IaC plan."""
        logger.info(f"📋 Running {{IAC_BINARY}} plan in {{self.work_dir}}...")
        self._generate_tfvars()
        self._run(["init", "-input=false"])
        self._run(["plan", "-input=false", "-out=tfplan"])

    def apply(self) -> None:
        """Run IaC apply."""
        logger.info(f"🚀 Running {{IAC_BINARY}} apply in {{self.work_dir}}...")
        self._run(["apply", "-input=false", "-auto-approve", "tfplan"])

    def plan_apply(self) -> None:
        """Run plan then apply."""
        self.plan()
        self.apply()

    def save_outputs(self) -> Path:
        """Save IaC outputs to iac-outputs/iac-outputs.json."""
        logger.info("💾 Saving IaC outputs...")
        result = subprocess.run(
            [IAC_BINARY, "output", "-json"],
            capture_output=True, text=True, check=True,
            cwd=self.work_dir,
        )
        outputs = json.loads(result.stdout)
        out_dir = Path("iac-outputs")
        out_dir.mkdir(parents=True, exist_ok=True)
        out_file = out_dir / "iac-outputs.json"
        out_file.write_text(json.dumps(outputs, indent=2), encoding="utf-8")
        logger.info(f"✅ Outputs saved to {{out_file}}")
        return out_file

    def _run(self, args: list[str]) -> None:
        cmd = [IAC_BINARY] + args
        logger.info(f"Running: {{' '.join(cmd)}} (in {{self.work_dir}})")
        subprocess.run(cmd, check=True, cwd=self.work_dir)
'''


def _gen_database_engine(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Database migration engine — runs Liquibase migrations via SSH tunnel.

Reads database configuration from foundry.json services (inline database
blocks), fetches IaC outputs to get bastion and database endpoint info,
opens an SSH tunnel through the bastion, fetches credentials from Secrets
Manager, and runs Liquibase through the tunnel.
"""

from __future__ import annotations

import json
import logging
import os
import shutil
import socket
import subprocess
import tempfile
import time
import urllib.request
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Default JDBC drivers and URL patterns per engine
_JDBC_DRIVERS: dict[str, str] = {{
    "mariadb": "org.mariadb.jdbc.Driver",
    "mysql": "com.mysql.cj.jdbc.Driver",
    "postgresql": "org.postgresql.Driver",
    "postgres": "org.postgresql.Driver",
}}

_JDBC_URL_TEMPLATES: dict[str, str] = {{
    "mariadb": "jdbc:mariadb://{{host}}:{{port}}/{{database}}?sslMode=trust",
    "mysql": "jdbc:mysql://{{host}}:{{port}}/{{database}}?sslMode=trust",
    "postgresql": "jdbc:postgresql://{{host}}:{{port}}/{{database}}?currentSchema={{schema}}",
    "postgres": "jdbc:postgresql://{{host}}:{{port}}/{{database}}?currentSchema={{schema}}",
}}

_DEFAULT_PORTS: dict[str, int] = {{
    "mariadb": 3306,
    "mysql": 3306,
    "postgresql": 5432,
    "postgres": 5432,
}}

# Liquibase download URL
_LIQUIBASE_VERSION = "4.29.2"
_LIQUIBASE_DOWNLOAD = f"https://github.com/liquibase/liquibase/releases/download/v{{_LIQUIBASE_VERSION}}/liquibase-{{_LIQUIBASE_VERSION}}.tar.gz"


def _is_port_open(host: str, port: int, timeout: float = 0.5) -> bool:
    """Check if a port is accepting connections."""
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


class DatabaseEngine:
    """Runs Liquibase database migrations through an SSH bastion tunnel."""

    def __init__(self, environment: str, prefix: str, session: Any):
        self.env = environment
        self.prefix = prefix
        self.session = session
        self.manifest = json.loads(Path("foundry.json").read_text(encoding="utf-8"))
        self._iac_outputs: dict[str, Any] | None = None
        self._tunnels: list[Any] = []  # subprocess.Popen instances
        self._key_file: str | None = None
        self._sg_rule_added: dict[str, str] | None = None  # tracks dynamic SG rule
        self._ensure_liquibase()

    def _ensure_liquibase(self) -> None:
        """Ensure Liquibase is available on PATH."""
        if shutil.which("liquibase"):
            return

        logger.info("Liquibase not found - installing...")
        install_dir = Path("/tmp/liquibase")
        install_dir.mkdir(parents=True, exist_ok=True)
        tar_path = install_dir / "liquibase.tar.gz"

        urllib.request.urlretrieve(_LIQUIBASE_DOWNLOAD, str(tar_path))
        subprocess.run(
            ["tar", "xzf", str(tar_path), "-C", str(install_dir)],
            check=True,
        )
        os.environ["PATH"] = f"{{install_dir}}:{{os.environ.get('PATH', '')}}"
        logger.info(f"Liquibase installed to {{install_dir}}")

    def _load_iac_outputs(self) -> dict[str, Any]:
        """Load IaC outputs from the artifact directory."""
        if self._iac_outputs is not None:
            return self._iac_outputs

        outputs_file = Path("iac-outputs/iac-outputs.json")
        if not outputs_file.exists():
            raise RuntimeError(
                f"IaC outputs not found at {{outputs_file}}. "
                "Ensure deploy-iac ran first and the artifact was downloaded."
            )

        raw = json.loads(outputs_file.read_text(encoding="utf-8"))
        # OpenTofu outputs are wrapped in {{"value": ..., "type": ...}}
        self._iac_outputs = {{
            k: v.get("value", v) if isinstance(v, dict) and "value" in v else v
            for k, v in raw.items()
        }}
        return self._iac_outputs

    def _fetch_bastion_key(self, secret_name: str) -> str:
        """Fetch the bastion SSH private key from Secrets Manager and write to a temp file."""
        if self._key_file:
            return self._key_file

        client = self.session.client("secretsmanager")
        response = client.get_secret_value(SecretId=secret_name)
        secret = json.loads(response["SecretString"])
        pem = secret.get("private_key_pem", response["SecretString"])

        key_path = Path(tempfile.mktemp(prefix="bastion-", suffix=".pem"))
        key_path.write_text(pem, encoding="utf-8")
        key_path.chmod(0o400)

        self._key_file = str(key_path)
        logger.info(f"Bastion SSH key written to {{key_path}}")
        return self._key_file

    def _open_tunnel(
        self,
        bastion_ip: str,
        bastion_user: str,
        key_file: str,
        remote_host: str,
        remote_port: int,
        local_port: int,
    ) -> subprocess.Popen:
        """Open an SSH tunnel through the bastion using the system ssh binary."""
        if _is_port_open("127.0.0.1", local_port):
            logger.info(f"Port {{local_port}} already open - tunnel may be active")
            return None

        cmd = [
            "ssh", "-N",
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "ServerAliveInterval=30",
            "-o", "ConnectTimeout=15",
            "-o", "ExitOnForwardFailure=yes",
            "-i", key_file,
            "-L", f"{{local_port}}:{{remote_host}}:{{remote_port}}",
            f"{{bastion_user}}@{{bastion_ip}}",
        ]

        logger.info(
            f"Opening SSH tunnel: localhost:{{local_port}} -> "
            f"{{remote_host}}:{{remote_port}} via {{bastion_ip}}"
        )
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )

        # Wait for tunnel to be ready (ssh stays alive as foreground process)
        for attempt in range(30):
            # Check if ssh exited with an error
            ret = proc.poll()
            if ret is not None:
                stderr = proc.stderr.read().decode() if proc.stderr else ""
                raise RuntimeError(
                    f"SSH tunnel process exited with code {{ret}}: {{stderr.strip()}}"
                )
            if _is_port_open("127.0.0.1", local_port):
                logger.info(f"SSH tunnel established on port {{local_port}}")
                return proc
            time.sleep(1)

        # Tunnel didn't open in time — kill and report
        proc.terminate()
        stderr = proc.stderr.read().decode() if proc.stderr else ""
        raise RuntimeError(
            f"SSH tunnel failed to open on port {{local_port}} after 30s: {{stderr.strip()}}"
        )

    def _collect_databases(self) -> dict[str, dict[str, Any]]:
        """Collect database configs from services (v0.5.0 inline) and top-level (v0.3.0)."""
        databases: dict[str, dict[str, Any]] = {{}}

        # v0.3.0: top-level databases block
        for db_name, db_cfg in self.manifest.get("databases", {{}}).items():
            if isinstance(db_cfg, dict):
                databases[db_name] = db_cfg

        # v0.5.0: inline database blocks in services
        for svc_name, svc_cfg in self.manifest.get("services", {{}}).items():
            if isinstance(svc_cfg, dict) and isinstance(svc_cfg.get("database"), dict):
                databases[svc_name] = svc_cfg["database"]

        return databases

    def _iac_db_key(self, manifest_name: str) -> str:
        """Derive the IaC key for a service (backends get -service, frontends get -frontend)."""
        services = self.manifest.get("services", {{}})
        svc_cfg = services.get(manifest_name, {{}})
        kind = svc_cfg.get("stack", {{}}).get("type", "backend")
        if kind == "backend":
            return f"{{manifest_name}}-service"
        elif kind == "frontend":
            return f"{{manifest_name}}-frontend"
        return manifest_name

    def _fetch_db_credentials(self, db_config: dict[str, Any]) -> dict[str, str]:
        """Fetch database credentials from Secrets Manager."""
        creds_cfg = db_config.get("credentials", {{}})
        secret_id = creds_cfg.get("secretId", "")

        if not secret_id:
            logger.warning("No secretId for database credentials")
            return {{}}

        client = self.session.client("secretsmanager")
        response = client.get_secret_value(SecretId=secret_id)
        return json.loads(response["SecretString"])

    def migrate_all(self) -> None:
        """Run migrations for all databases through SSH tunnel."""
        databases = self._collect_databases()
        if not databases:
            logger.info("No databases found in manifest")
            return

        logger.info(f"Found {{len(databases)}} database(s) to migrate")

        # Load IaC outputs for bastion and database endpoints
        iac = self._load_iac_outputs()
        bastion_info = iac.get("bastion", {{}})
        db_outputs = iac.get("databases", {{}})
        bastion_ip = bastion_info.get("public_ip") or bastion_info.get("elastic_ip")

        if not bastion_ip:
            raise RuntimeError("No bastion IP found in IaC outputs")

        # Fetch bastion SSH key
        key_secret = bastion_info.get("ssh_key_secret_name")
        if not key_secret:
            raise RuntimeError("No bastion SSH key secret name in IaC outputs")
        key_file = self._fetch_bastion_key(key_secret)

        # Dynamically whitelist runner IP in bastion security group for SSH
        sg_id = bastion_info.get("security_group_id")
        if sg_id:
            self._whitelist_runner_ip(sg_id)
        else:
            logger.warning("No bastion security_group_id in IaC outputs — "
                           "SSH may fail if runner IP is not whitelisted")

        try:
            for db_name, db_config in databases.items():
                self._migrate_with_tunnel(
                    db_name, db_config, bastion_ip, key_file, db_outputs,
                )
        finally:
            self._cleanup()

    def _get_runner_ip(self) -> str:
        """Get the public IP of the current runner."""
        try:
            resp = urllib.request.urlopen("https://checkip.amazonaws.com", timeout=10)
            return resp.read().decode().strip()
        except Exception:
            resp = urllib.request.urlopen("https://ifconfig.me/ip", timeout=10)
            return resp.read().decode().strip()

    def _whitelist_runner_ip(self, security_group_id: str) -> None:
        """Add the runner's public IP to the bastion security group for SSH access."""
        try:
            runner_ip = self._get_runner_ip()
            logger.info(f"Runner public IP: {{runner_ip}}")

            ec2_client = self.session.client("ec2")
            cidr = f"{{runner_ip}}/32"
            ec2_client.authorize_security_group_ingress(
                GroupId=security_group_id,
                IpPermissions=[{{
                    "IpProtocol": "tcp",
                    "FromPort": 22,
                    "ToPort": 22,
                    "IpRanges": [{{"CidrIp": cidr, "Description": "CI runner - temporary"}}],
                }}],
            )
            self._sg_rule_added = {{"sg_id": security_group_id, "cidr": cidr}}
            logger.info(f"✅ Added SSH ingress rule for {{cidr}} to {{security_group_id}}")
        except Exception as e:
            if "InvalidPermission.Duplicate" in str(e):
                logger.info("Runner IP already whitelisted in bastion SG")
            else:
                logger.warning(f"⚠️ Could not whitelist runner IP: {{e}}")

    def _revoke_runner_ip(self) -> None:
        """Remove the runner's IP from the bastion security group."""
        if not self._sg_rule_added:
            return
        try:
            ec2_client = self.session.client("ec2")
            sg_id = self._sg_rule_added["sg_id"]
            cidr = self._sg_rule_added["cidr"]
            ec2_client.revoke_security_group_ingress(
                GroupId=sg_id,
                IpPermissions=[{{
                    "IpProtocol": "tcp",
                    "FromPort": 22,
                    "ToPort": 22,
                    "IpRanges": [{{"CidrIp": cidr}}],
                }}],
            )
            logger.info(f"✅ Removed SSH ingress rule for {{cidr}} from {{sg_id}}")
            self._sg_rule_added = None
        except Exception as e:
            logger.warning(f"⚠️ Could not remove runner IP from SG: {{e}}")

    def _migrate_with_tunnel(
        self,
        db_name: str,
        db_config: dict[str, Any],
        bastion_ip: str,
        key_file: str,
        db_outputs: dict[str, Any],
    ) -> None:
        """Migrate a single database through an SSH tunnel."""
        engine = db_config.get("engine", "mariadb")
        changelog = db_config.get("changelog")
        schema = db_config.get("schema", "")

        if not changelog:
            logger.warning(f"No changelog for database {{db_name}} - skipping")
            return

        logger.info(f"Migrating database: {{db_name}} ({{engine}})")

        # Get database endpoint from IaC outputs (IaC uses convention keys)
        iac_key = self._iac_db_key(db_name)
        db_out = db_outputs.get(iac_key, db_outputs.get(db_name, {{}}))
        remote_host = db_out.get("address", "")
        remote_port = int(db_out.get("port", _DEFAULT_PORTS.get(engine, 3306)))

        if not remote_host:
            logger.error(f"No database endpoint found in IaC outputs for {{db_name}} (tried key '{{iac_key}}')") 
            return

        # Pick a local port for the tunnel
        local_port = self._find_free_port()

        # Open SSH tunnel (retry up to 3 times — first attempt frequently fails in CI)
        tunnel = None
        max_tunnel_retries = 3
        for tunnel_attempt in range(1, max_tunnel_retries + 1):
            try:
                tunnel = self._open_tunnel(
                    bastion_ip=bastion_ip,
                    bastion_user="ec2-user",
                    key_file=key_file,
                    remote_host=remote_host,
                    remote_port=remote_port,
                    local_port=local_port,
                )
                break
            except RuntimeError as e:
                if tunnel_attempt < max_tunnel_retries:
                    logger.warning(
                        f"SSH tunnel attempt {{tunnel_attempt}}/{{max_tunnel_retries}} failed: {{e}} — retrying in 5s"
                    )
                    time.sleep(5)
                    # Pick a new port in case the old one is stuck
                    local_port = self._find_free_port()
                else:
                    raise
        if tunnel:
            self._tunnels.append(tunnel)

        # Fetch credentials from Secrets Manager
        creds = self._fetch_db_credentials(db_config)
        if not creds:
            logger.error(f"Could not fetch credentials for {{db_name}}")
            return

        username = creds.get("username", "")
        password = creds.get("password", "")
        database = creds.get("database", creds.get("dbname", db_name))
        driver = _JDBC_DRIVERS.get(engine, "")

        url_template = _JDBC_URL_TEMPLATES.get(engine, "")
        url = url_template.format(
            host="127.0.0.1",
            port=local_port,
            database=database,
            schema=schema or "public",
        )

        env = os.environ.copy()
        env["LIQUIBASE_COMMAND_URL"] = url
        env["LIQUIBASE_COMMAND_USERNAME"] = username
        env["LIQUIBASE_COMMAND_PASSWORD"] = password
        if schema:
            env["LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME"] = schema

        args = [
            "liquibase",
            f"--changelog-file={{changelog}}",
            f"--driver={{driver}}",
            "update",
        ]

        log_args = list(args)
        logger.info(f"Running: {{' '.join(log_args)}}")
        logger.info(f"  URL: jdbc:...://127.0.0.1:{{local_port}}/{{database}} (via tunnel)")
        subprocess.run(args, check=True, env=env)
        logger.info(f"Database {{db_name}} migrated successfully")

    @staticmethod
    def _find_free_port() -> int:
        """Find an available local port."""
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("", 0))
            return s.getsockname()[1]

    def _cleanup(self) -> None:
        """Close all SSH tunnels, remove temp key file, and revoke SG rule."""
        for proc in self._tunnels:
            if proc and proc.poll() is None:
                proc.terminate()
                try:
                    proc.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    proc.kill()
        self._tunnels.clear()

        if self._key_file and Path(self._key_file).exists():
            Path(self._key_file).unlink(missing_ok=True)
            logger.info("Cleaned up bastion SSH key file")

        self._revoke_runner_ip()
'''


def _gen_change_detector(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Change detector — determines which services need deployment.

Uses git diff to find changed files and maps them to services using
watch paths from the convention engine.
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from typing import Any

from core.conventions import DeploymentProfile, resolve_all_profiles
from core.manifest_reader import Manifest

logger = logging.getLogger(__name__)


def detect_changes(
    git_before: str,
    git_after: str,
    branch: str,
    force: str = "",
) -> dict[str, Any]:
    """Detect which services changed and need deployment.

    Returns a dict with:
      - services: list of service names that changed
      - environment: resolved environment name
      - has_db_changes: whether any database changelog paths changed
    """
    manifest = Manifest.load()
    environment = manifest.resolve_environment(branch)

    if not environment:
        logger.info(f"ℹ️ Branch '{{branch}}' does not map to any environment — skipping")
        return {{"services": [], "environment": "", "has_db_changes": "false"}}

    profiles = resolve_all_profiles(manifest)

    # Force-deploy specific services
    if force:
        forced = [s.strip() for s in force.split(",") if s.strip()]
        logger.info(f"⚡ Force deploying: {{forced}}")
        return {{
            "services": forced,
            "environment": environment,
            "has_db_changes": str(any(
                profiles.get(s, None) and profiles[s].database for s in forced
            )).lower(),
        }}

    # Get changed files
    changed_files = _get_changed_files(git_before, git_after)
    if not changed_files:
        logger.info("ℹ️ No files changed")
        return {{"services": [], "environment": environment, "has_db_changes": "false"}}

    logger.info(f"📝 {{len(changed_files)}} files changed")

    # Match to services
    affected: list[str] = []
    for name, profile in profiles.items():
        if not profile.is_deployable:
            continue
        for pattern in profile.watch_paths:
            if any(re.match(pattern, f) for f in changed_files):
                affected.append(name)
                break

    # Check for IaC changes (deploys everything)
    ci_dir = manifest.ci.get("iacDir", "ci/iac")
    if any(f.startswith(f"{{ci_dir}}/") for f in changed_files):
        logger.info("🏗️ IaC changes detected — all services will deploy")
        affected = [n for n, p in profiles.items() if p.is_deployable]

    # Check for database changes — either changelog files changed directly,
    # or an affected service has a database (e.g. IaC changes force all deploys)
    db_paths = [db.get("changelog", "").rsplit("/", 1)[0] for db in manifest.databases.values()]
    has_db_changes = any(
        any(f.startswith(dp) for dp in db_paths if dp)
        for f in changed_files
    ) or any(
        profiles.get(s) and profiles[s].database for s in affected
    )

    logger.info(f"🎯 Affected services: {{affected}}")
    return {{
        "services": affected,
        "environment": environment,
        "has_db_changes": str(has_db_changes).lower(),
    }}


def _get_changed_files(before: str, after: str) -> list[str]:
    """Get list of changed files between two git commits."""
    try:
        result = subprocess.run(
            ["git", "diff", "--name-only", before, after],
            capture_output=True, text=True, check=True,
        )
        return [f.strip() for f in result.stdout.strip().splitlines() if f.strip()]
    except subprocess.CalledProcessError as e:
        logger.warning(f"⚠️ git diff failed: {{e}}")
        return []


def write_github_outputs(result: dict[str, Any]) -> None:
    """Write detection results to GITHUB_OUTPUT if running in Actions."""
    github_output = os.environ.get("GITHUB_OUTPUT")
    if not github_output:
        logger.info("ℹ️ Not in GitHub Actions — printing results to stdout")
        print(json.dumps(result, indent=2))
        return

    with open(github_output, "a") as f:
        f.write(f"services={{json.dumps(result['services'])}}\\n")
        f.write(f"environment={{result['environment']}}\\n")
        f.write(f"has_db_changes={{result['has_db_changes']}}\\n")

    logger.info(f"✅ GitHub outputs written: {{len(result['services'])}} services, env={{result['environment']}}")
'''


def _gen_deploy_cli(manifest: ProjectManifest, header: str) -> str:
    return f'''{header}
"""Unified deployment CLI.

Single entry point for all deployment operations:
  deploy.py detect   — detect changed services
  deploy.py iac      — run IaC plan/apply
  deploy.py migrate  — run database migrations
  deploy.py service  — deploy a single service
  deploy.py all      — deploy everything
"""

from __future__ import annotations

import logging
import sys

import boto3
import click

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)


@click.group()
def cli():
    """Foundry deployment CLI — manifest-driven, convention-based."""
    pass


@cli.command()
@click.option("--git-before", required=True, help="Git SHA before the push")
@click.option("--git-after", required=True, help="Git SHA after the push")
@click.option("--branch", required=True, help="Git branch name")
@click.option("--force", default="", help="Comma-separated service names to force deploy")
def detect(git_before: str, git_after: str, branch: str, force: str):
    """Detect which services need deployment based on git changes."""
    from orchestration.change_detector import detect_changes, write_github_outputs

    result = detect_changes(git_before, git_after, branch, force)
    write_github_outputs(result)


@cli.command()
@click.option("--environment", required=True, help="Target environment (prod, dev, test)")
@click.option("--operation", required=True,
              type=click.Choice(["plan", "apply", "plan-apply"]),
              help="IaC operation")
def iac(environment: str, operation: str):
    """Run IaC (OpenTofu/Terraform) operations."""
    from engines.iac_engine import IacEngine
    from core.manifest_reader import Manifest

    manifest = Manifest.load()
    session = boto3.Session()
    engine = IacEngine(environment, manifest.prefix, session)

    if operation == "plan":
        engine.plan()
    elif operation == "apply":
        engine.apply()
    elif operation == "plan-apply":
        engine.plan_apply()

    engine.save_outputs()


@cli.command(name="repackage-lambdas")
@click.option("--iac-dir", default="ci/iac", help="Path to IaC directory")
def repackage_lambdas(iac_dir: str):
    """Repackage Lambda functions whose source files are newer than their zip."""
    import os
    import subprocess
    import zipfile
    from pathlib import Path

    functions_dir = Path(iac_dir) / "modules" / "lambda" / "functions"
    if not functions_dir.exists():
        logger.info("No Lambda functions directory found, skipping")
        return

    repackaged = 0
    for func_dir in sorted(functions_dir.iterdir()):
        if not func_dir.is_dir():
            continue

        # Find the zip file
        zips = list(func_dir.glob("*.zip"))
        if not zips:
            continue
        zip_path = zips[0]
        zip_mtime = zip_path.stat().st_mtime

        # Check if any source file is newer than the zip
        source_exts = {{".py", ".js", ".ts", ".json", ".txt", ".html", ".css"}}
        needs_repackage = False
        for src in func_dir.iterdir():
            if src.suffix in source_exts and src.name != "package.ps1" and src.stat().st_mtime > zip_mtime:
                needs_repackage = True
                break

        if not needs_repackage:
            continue

        logger.info(f"📦 Repackaging {{func_dir.name}}...")

        # Check for requirements.txt — if present, install deps
        reqs = func_dir / "requirements.txt"
        build_dir = func_dir / "_build"

        if build_dir.exists():
            import shutil
            shutil.rmtree(build_dir)
        build_dir.mkdir()

        if reqs.exists():
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "-r", str(reqs), "-t", str(build_dir), "--quiet"],
                check=True,
            )

        # Copy source files
        for src in func_dir.iterdir():
            if src.suffix in source_exts and src.name != "package.ps1":
                import shutil
                shutil.copy2(src, build_dir / src.name)

        # Create zip
        zip_path.unlink(missing_ok=True)
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for root, _dirs, files in os.walk(build_dir):
                for file in files:
                    file_path = Path(root) / file
                    arcname = file_path.relative_to(build_dir)
                    zf.write(file_path, arcname)

        # Clean up
        import shutil
        shutil.rmtree(build_dir)
        size_mb = zip_path.stat().st_size / (1024 * 1024)
        logger.info(f"   ✅ {{zip_path.name}} ({{size_mb:.2f}} MB)")
        repackaged += 1

    if repackaged:
        logger.info(f"📦 Repackaged {{repackaged}} Lambda function(s)")
    else:
        logger.info("📦 All Lambda packages are up to date")


@cli.command()
@click.option("--environment", required=True, help="Target environment")
def migrate(environment: str):
    """Run database migrations for all databases."""
    from engines.database_engine import DatabaseEngine

    session = boto3.Session()
    from core.manifest_reader import Manifest
    manifest = Manifest.load()
    engine = DatabaseEngine(environment, manifest.prefix, session)
    engine.migrate_all()


@cli.command()
@click.option("--name", required=True, help="Service name from foundry.json")
@click.option("--environment", required=True, help="Target environment")
@click.option("--operation", required=True,
              type=click.Choice(["build-push", "deploy", "build-deploy"]),
              help="Operation to perform")
def service(name: str, environment: str, operation: str):
    """Deploy a single service."""
    from core.conventions import resolve_all_profiles
    from core.manifest_reader import Manifest
    from engines.ecs_engine import EcsEngine
    from engines.s3_static_engine import S3StaticEngine

    manifest = Manifest.load()
    profiles = resolve_all_profiles(manifest)

    if name not in profiles:
        logger.error(f"❌ Unknown service: {{name}}")
        sys.exit(1)

    profile = profiles[name]
    session = boto3.Session()

    if profile.strategy == "service":
        engine = EcsEngine(profile, environment, manifest.prefix, session)
        if operation == "build-push":
            engine.build_and_push()
        elif operation == "deploy":
            engine.deploy()
        elif operation == "build-deploy":
            image_uri = engine.build_and_push()
            engine.deploy(image_uri)

    elif profile.strategy == "static":
        engine = S3StaticEngine(profile, environment, manifest.prefix, session)
        if operation in ("build-deploy",):
            engine.build_and_deploy()
        else:
            logger.warning(f"⚠️ Operation '{{operation}}' not applicable for static strategy")

    else:
        logger.error(f"❌ Service {{name}} has strategy '{{profile.strategy}}' — not deployable")
        sys.exit(1)

    logger.info("🎉 Operation completed successfully")


@cli.command(name="all")
@click.option("--environment", required=True, help="Target environment")
def deploy_all(environment: str):
    """Deploy all services (force full deployment)."""
    from core.conventions import resolve_all_profiles
    from core.manifest_reader import Manifest

    manifest = Manifest.load()
    profiles = resolve_all_profiles(manifest)

    deployable = {{n: p for n, p in profiles.items() if p.is_deployable}}
    logger.info(f"🚀 Deploying all {{len(deployable)}} services to {{environment}}")

    # TODO: respect dependency ordering
    for name, profile in sorted(deployable.items()):
        logger.info(f"\\n{'=' * 60}")
        logger.info(f"Deploying {{name}} ({{profile.strategy}})")
        logger.info(f"{'=' * 60}")
        # Each service deploy is done via the 'service' command logic
        # For now, call it directly
        from click.testing import CliRunner
        runner = CliRunner()
        if profile.strategy == "service":
            runner.invoke(service, ["--name", name, "--environment", environment, "--operation", "build-deploy"])
        elif profile.strategy == "static":
            runner.invoke(service, ["--name", name, "--environment", environment, "--operation", "build-deploy"])


if __name__ == "__main__":
    cli()
'''


# ── Registry of all files to generate ────────────────────────────────────

_FILE_GENERATORS: dict[str, Any] = {
    "requirements.txt": _gen_requirements,
    "deploy.py": _gen_deploy_cli,
    "core/__init__.py": _gen_core_init,
    "core/manifest_reader.py": _gen_manifest_reader,
    "core/conventions.py": _gen_conventions,
    "core/secrets.py": _gen_secrets,
    "core/tfvars_generator.py": _gen_tfvars_generator,
    "engines/__init__.py": _gen_engines_init,
    "engines/ecs_engine.py": _gen_ecs_engine,
    "engines/s3_static_engine.py": _gen_s3_static_engine,
    "engines/iac_engine.py": _gen_iac_engine,
    "engines/database_engine.py": _gen_database_engine,
    "orchestration/__init__.py": _gen_orchestration_init,
    "orchestration/change_detector.py": _gen_change_detector,
}


__all__ = [
    "generate_scripts",
]
