"""Tfvars generator — produces ``{env}.auto.tfvars`` from config in Secrets Manager.

Reads the project manifest for service identity, naming, and deployment
strategies, then pulls the full infrastructure configuration from AWS
Secrets Manager to generate OpenTofu variable files.

**Data Sources:**

- **foundry.json** (committed):
  service names, kinds, deployment strategies, ecosystem prefix
- **Secrets Manager** ``{name_prefix}/iac/config``:
  all infrastructure configuration — compute, ALB, security groups,
  IAM policies, databases, lambdas, eventbridge, etc.
- **AWS CLI** (at generation time):
  ``account_id`` (STS), ``hosted_zone_id`` (Route 53)

**Template Variables:**

All IAC configuration supports these placeholders:

- ``{prefix}`` — Platform prefix (e.g., ``aap``)
- ``{env}`` — Environment name (e.g., ``prod``)
- ``{name_prefix}`` — ``{prefix}-{env}`` (e.g., ``aap-prod``)
- ``{account_id}`` — AWS account ID (resolved from STS)
- ``{region}`` — AWS region
- ``{iac_name}`` — IaC service name (e.g., ``microlith-service``)
- ``{manifest_name}`` — Manifest service name (e.g., ``microlith``)

**Data Flow:**

::

    foundry.json             AWS Secrets Manager
      ├── prefix             {name_prefix}/iac/config
      ├── name                 ├── region, tags, domain, bastion
      └── services (names)     ├── services.{name} (IAC blocks)
            ↓                  ├── lambda_functions, eventbridge_rules
            merge              └── emp_ip_whitelist
              ↓
    AWS CLI (live resolution)
      ├── account_id (STS)
      └── hosted_zone_id (Route 53)
              ↓
    naming convention applied
    template variables resolved
    cross-references resolved
              ↓
    ci/iac/{env}/{env}.auto.tfvars
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from foundry_cli.core.project.manifest import ProjectManifest
from foundry_cli.generators.conventions import DeploymentProfile, resolve_all_profiles

logger = logging.getLogger(__name__)

# ── Header template ──────────────────────────────────────────────────────

_HEADER = """\
# ════════════════════════════════════════════════════════════════════════════
# GENERATED BY: foundry generate tfvars
# Manual edits will be overwritten on next generation.
# Regenerate with: foundry generate tfvars
# Source: foundry.json (schemaVersion {schema_version})
# ════════════════════════════════════════════════════════════════════════════
"""


def _section(title: str) -> str:
    """Render an HCL section header comment."""
    return (
        f"# {'=' * 76}\n"
        f"# {title}\n"
        f"# {'=' * 76}"
    )


def _subsection(name: str) -> str:
    """Render a subsection comment line for inside maps."""
    sep_len = max(0, 66 - len(name))
    return f"  # ── {name} {'─' * sep_len}"


# ── HCL Serializer ──────────────────────────────────────────────────────
# A minimal recursive serializer for OpenTofu .tfvars syntax.
# Handles: strings, numbers, bools, lists, dicts (objects/maps).
# Keys starting with '_' or '$' are filtered (used for JSON comments).
# None values are omitted.


def _hcl(value: Any, indent: int = 0) -> str:
    """Serialize a Python value to HCL literal syntax."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:g}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    if value is None:
        return "null"
    if isinstance(value, (list, tuple)):
        return _hcl_list(list(value), indent)
    if isinstance(value, dict):
        return _hcl_object(value, indent)
    return repr(value)


def _hcl_list(items: list[Any], indent: int) -> str:
    """Serialize a list to HCL.

    Short lists of scalars are rendered inline (``[a, b, c]``).
    Long lists or lists containing objects are rendered multi-line.
    """
    if not items:
        return "[]"

    # Short scalar lists → inline
    if all(isinstance(v, (str, int, float, bool)) for v in items):
        inline = ", ".join(_hcl(v) for v in items)
        if len(inline) < 70:
            return f"[{inline}]"

    # Multi-line
    pad = "  " * (indent + 1)
    end_pad = "  " * indent
    lines = ["["]
    for item in items:
        serialized = _hcl(item, indent + 1)
        lines.append(f"{pad}{serialized},")
    lines.append(f"{end_pad}]")
    return "\n".join(lines)


def _hcl_object(data: dict[str, Any], indent: int) -> str:
    """Serialize a dict to HCL object with aligned ``=`` signs.

    Skips keys starting with ``_`` or ``$`` (JSON comment convention).
    Skips keys whose value is ``None``.
    Adds blank lines before complex (multi-line) values for readability.
    """
    if not data:
        return "{}"

    items = [
        (k, v) for k, v in data.items()
        if not str(k).startswith(("_", "$")) and v is not None
    ]
    if not items:
        return "{}"

    pad = "  " * (indent + 1)
    end_pad = "  " * indent

    # Alignment: pad shorter keys so '=' signs line up
    max_key_len = max(len(str(k)) for k, _ in items)

    lines: list[str] = ["{"]
    prev_complex = False

    for i, (key, value) in enumerate(items):
        serialized = _hcl(value, indent + 1)
        is_complex = "\n" in serialized

        # Blank line before complex values for visual grouping
        if is_complex and i > 0:
            lines.append("")
        elif prev_complex and i > 0 and not is_complex:
            lines.append("")

        spacing = " " * (max_key_len - len(str(key)))
        lines.append(f"{pad}{key}{spacing} = {serialized}")

        prev_complex = is_complex

    lines.append(f"{end_pad}}}")
    return "\n".join(lines)


# ── Naming Convention ────────────────────────────────────────────────────


def iac_service_name(manifest_name: str, kind: str) -> str:
    """Derive the IaC key for an ECS service from manifest name + kind.

    Backends get ``-service`` suffix, frontends get ``-frontend``.

    Examples::

        iac_service_name("platform-microlith", "backend")  → "platform-microlith-service"
        iac_service_name("hub", "frontend")                 → "hub-frontend"
    """
    if kind == "backend":
        return f"{manifest_name}-service"
    if kind == "frontend":
        return f"{manifest_name}-frontend"
    return manifest_name


def iac_static_site_name(manifest_name: str) -> str:
    """Derive the IaC key for a static site from manifest name.

    Always adds ``-frontend`` suffix.

    Example::

        iac_static_site_name("hub")  → "hub-frontend"
    """
    if manifest_name.endswith("-frontend"):
        return manifest_name
    return f"{manifest_name}-frontend"


def _build_name_map(
    profiles: dict[str, DeploymentProfile],
) -> dict[str, str]:
    """Build a mapping of manifest name → IaC name for all deployable services.

    Used to resolve cross-references like ``service:platform-microlith`` →
    ``service:platform-microlith-service``.
    """
    name_map: dict[str, str] = {}
    for manifest_name, profile in profiles.items():
        if not profile.is_deployable:
            continue
        if profile.strategy == "static":
            name_map[manifest_name] = iac_static_site_name(manifest_name)
        else:
            name_map[manifest_name] = iac_service_name(manifest_name, profile.kind)
    return name_map


# ── Reference & Template Resolution ─────────────────────────────────────


def _resolve_refs(value: Any, name_map: dict[str, str]) -> Any:
    """Walk a data structure and resolve ``service:XXX`` cross-references.

    Replaces ``service:{manifest_name}`` with ``service:{iac_name}`` using
    the provided name mapping.
    """
    if isinstance(value, str):
        for manifest_name, iac_name in name_map.items():
            value = value.replace(f"service:{manifest_name}", f"service:{iac_name}")
        return value
    if isinstance(value, dict):
        return {k: _resolve_refs(v, name_map) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_resolve_refs(v, name_map) for v in value]
    return value


def _resolve_templates(value: Any, variables: dict[str, str]) -> Any:
    """Walk a data structure and resolve ``{placeholder}`` templates.

    Supported placeholders:

    - ``{prefix}`` — Platform prefix (e.g., ``aap``)
    - ``{env}`` — Environment name (e.g., ``prod``)
    - ``{name_prefix}`` — ``{prefix}-{env}`` (e.g., ``aap-prod``)
    - ``{account_id}`` — AWS account ID (resolved from STS)
    - ``{region}`` — AWS region (from env config)
    - ``{iac_name}`` — IaC service name (e.g., ``platform-microlith-service``)
    - ``{manifest_name}`` — Manifest service name (e.g., ``platform-microlith``)
    """
    if isinstance(value, str):
        try:
            return value.format_map(variables)
        except (KeyError, ValueError):
            return value
    if isinstance(value, dict):
        return {k: _resolve_templates(v, variables) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_resolve_templates(v, variables) for v in value]
    return value


# ── Commented Map Renderer ───────────────────────────────────────────────


def _render_commented_map(
    map_name: str,
    items: dict[str, dict[str, Any]],
) -> str:
    """Render a top-level HCL map with per-entry comment separators.

    Produces output like::

        services = {
          # ── platform-microlith-service ────────────────────────────────
          platform-microlith-service = {
            ...
          }

          # ── nlp-profanity-service ─────────────────────────────────────
          nlp-profanity-service = {
            ...
          }
        }
    """
    if not items:
        return f"{map_name} = {{}}"

    lines: list[str] = [f"{map_name} = {{"]

    for iac_key, config in items.items():
        lines.append("")
        lines.append(_subsection(iac_key))
        serialized = _hcl(config, 1)
        lines.append(f"  {iac_key} = {serialized}")

    lines.append("}")
    return "\n".join(lines)


# ── AWS Resolution ───────────────────────────────────────────────────────


def _load_iac_config(
    secret_id: str,
    region: str | None = None,
) -> dict[str, Any]:
    """Load the full IAC configuration from Secrets Manager.

    The secret is expected to contain a JSON object with keys like:

    - ``region``, ``tags``, ``ses_identity_arn``, ``domain``, ``bastion``
    - ``emp_ip_whitelist``
    - ``services`` — per-service IAC blocks keyed by manifest name
    - ``lambda_functions``, ``eventbridge_rules``

    Args:
        secret_id: The secret name (e.g., ``aap-prod/iac/config``).
        region: Optional region override.

    Returns:
        The parsed IAC configuration dict.

    Raises:
        FoundryError: If the secret cannot be read or parsed.
    """
    from foundry_cli.core.aws import get_secret_json

    logger.info("Loading IAC config from secret: %s", secret_id)
    config = get_secret_json(secret_id, region=region)

    if not isinstance(config, dict):
        from foundry_cli.core.errors import FoundryError
        raise FoundryError(
            f"IAC config secret '{secret_id}' is not a JSON object "
            f"(got {type(config).__name__})"
        )

    logger.info(
        "Loaded IAC config: %d top-level keys, %d service configs",
        len(config),
        len(config.get("services", {})),
    )
    return config


def _resolve_aws_identity(
    *,
    region: str,
    account_id: str,
    domain_name: str,
    hosted_zone_id: str,
) -> tuple[str, str]:
    """Resolve account_id and hosted_zone_id from the AWS CLI.

    Falls back to the provided values when the CLI is unavailable.

    Returns:
        (account_id, hosted_zone_id)
    """
    try:
        from foundry_cli.core.aws import (
            resolve_caller_identity,
            resolve_hosted_zone_id,
        )
    except ImportError:
        logger.debug("core.aws not available — skipping AWS resolution")
        return account_id, hosted_zone_id

    # ── account_id ───────────────────────────────────────────────────
    if not account_id:
        try:
            identity = resolve_caller_identity(region=region)
            account_id = identity.account_id
            logger.info("Resolved account_id from AWS: %s", account_id)
        except Exception as exc:
            logger.warning("Could not resolve account_id from AWS: %s", exc)
            account_id = "000000000000"

    # ── hosted_zone_id ───────────────────────────────────────────────
    if not hosted_zone_id and domain_name:
        try:
            hosted_zone_id = resolve_hosted_zone_id(
                domain_name, region=region,
            )
            logger.info(
                "Resolved hosted_zone_id for %s: %s",
                domain_name, hosted_zone_id,
            )
        except Exception as exc:
            logger.warning(
                "Could not resolve hosted_zone_id for %s: %s",
                domain_name, exc,
            )

    return account_id, hosted_zone_id


# ── Main Generator ───────────────────────────────────────────────────────


def generate_tfvars(
    manifest: ProjectManifest,
    env_name: str,
    *,
    resolve_aws: bool = True,
) -> str:
    """Generate a complete ``{env}.auto.tfvars`` file.

    Reads structural metadata from ``foundry.json`` (service names, kinds,
    deployment strategies) and pulls all infrastructure configuration from
    the IAC config secret in AWS Secrets Manager.

    The secret name is derived as ``{prefix}-{env}/iac/config`` unless
    overridden via ``ci.environments.{env}.iacConfigSecret`` in the manifest.

    Template placeholders and cross-references are resolved automatically.

    Args:
        manifest: A loaded ``ProjectManifest``.
        env_name: Target environment name (e.g., ``prod``).
        resolve_aws: When True, load IAC config from Secrets Manager
            and resolve ``account_id`` / ``hosted_zone_id`` from AWS.
            Set False for offline/testing use with inline ``iac`` blocks.

    Returns:
        The full HCL tfvars content as a string.
    """
    schema_version = manifest.data.get("schemaVersion", "0.3.0")
    prefix = manifest.prefix or "app"
    name_prefix = f"{prefix}-{env_name}"

    # Environment-level manifest configuration (structural only)
    env_cfg: dict[str, Any] = (
        manifest.data
        .get("ci", {})
        .get("environments", {})
        .get(env_name, {})
    )

    # ── Load IAC config ──────────────────────────────────────────────────
    # Primary source: Secrets Manager.  Fallback: inline iac block in manifest.
    iac_config: dict[str, Any] = {}
    iac_secret_name = env_cfg.get(
        "iacConfigSecret",
        f"{name_prefix}/iac/config",
    )

    if resolve_aws:
        try:
            iac_config = _load_iac_config(iac_secret_name)
        except Exception as exc:
            logger.warning(
                "Could not load IAC config from '%s': %s  "
                "— falling back to inline foundry.json iac block",
                iac_secret_name, exc,
            )

    # Fallback: inline iac block in foundry.json (for dev/offline)
    if not iac_config:
        iac_config = env_cfg.get("iac", {})

    region = iac_config.get("region", "us-east-1")

    # ── Resolve identity from AWS CLI ────────────────────────────────────
    domain_cfg: dict[str, Any] = iac_config.get("domain", {})
    account_id = ""
    hosted_zone_id = domain_cfg.get("hosted_zone_id", "")

    if resolve_aws:
        account_id, hosted_zone_id = _resolve_aws_identity(
            region=region,
            account_id=account_id,
            domain_name=domain_cfg.get("name", ""),
            hosted_zone_id=hosted_zone_id,
        )

    emp_ip_whitelist = iac_config.get("emp_ip_whitelist", [])

    # Resolve deployment profiles from manifest (convention engine)
    profiles = resolve_all_profiles(manifest.data)
    name_map = _build_name_map(profiles)

    # Global template variables (includes AWS-resolved values)
    global_vars: dict[str, str] = {
        "prefix": prefix,
        "env": env_name,
        "name_prefix": name_prefix,
        "account_id": account_id,
        "region": region,
    }

    # ── Platform block ───────────────────────────────────────────────────
    platform_tags = {**iac_config.get("tags", {}), "Environment": env_name}
    platform_block: dict[str, Any] = {
        "name": manifest.name or "Platform",
        "prefix": prefix,
        "environment": env_name,
        "region": region,
        "account_id": account_id,
        "emp_ip_whitelist": emp_ip_whitelist,
        "tags": platform_tags,
    }

    # ── Per-service IAC from config secret ───────────────────────────────
    secret_services: dict[str, Any] = iac_config.get("services", {})
    raw_services: dict[str, Any] = manifest.data.get("services", {})

    # ── ECS Services ─────────────────────────────────────────────────────
    ecs_services: dict[str, dict[str, Any]] = {}

    for manifest_name, profile in sorted(profiles.items()):
        if not profile.is_deployable:
            continue
        if profile.strategy == "static":
            continue  # Goes to static_sites

        # IAC config: prefer secret, fall back to inline foundry.json
        svc_iac: dict[str, Any] = secret_services.get(manifest_name, {})
        if not svc_iac:
            raw_svc = raw_services.get(manifest_name, {})
            svc_iac = raw_svc.get("deploy", {}).get("iac", {})

        if not svc_iac:
            logger.warning(
                "Service '%s' has no deploy.iac — skipping",
                manifest_name,
            )
            continue

        iac_key = iac_service_name(manifest_name, profile.kind)

        # Per-service template variables
        svc_vars: dict[str, str] = {
            **global_vars,
            "iac_name": iac_key,
            "manifest_name": manifest_name,
        }

        # Resolve templates and cross-references
        resolved = _resolve_templates(svc_iac, svc_vars)
        resolved = _resolve_refs(resolved, name_map)

        ecs_services[iac_key] = resolved

    # ── Static Sites ─────────────────────────────────────────────────────
    static_sites: dict[str, dict[str, Any]] = {}

    for manifest_name, profile in sorted(profiles.items()):
        if profile.strategy != "static":
            continue

        # IAC config: prefer secret, fall back to inline foundry.json
        site_iac: dict[str, Any] = secret_services.get(manifest_name, {})
        if not site_iac:
            raw_svc = raw_services.get(manifest_name, {})
            site_iac = raw_svc.get("deploy", {}).get("iac", {})

        if not site_iac:
            logger.warning(
                "Static site '%s' has no deploy.iac — skipping",
                manifest_name,
            )
            continue

        iac_key = iac_static_site_name(manifest_name)

        svc_vars = {
            **global_vars,
            "iac_name": iac_key,
            "manifest_name": manifest_name,
        }

        resolved = _resolve_templates(site_iac, svc_vars)
        static_sites[iac_key] = resolved

    # ── Assemble output ──────────────────────────────────────────────────
    parts: list[str] = []

    # Header
    parts.append(_HEADER.format(schema_version=schema_version))

    # Platform
    parts.append(_section("Platform Configuration"))
    parts.append("")
    parts.append(f"platform = {_hcl(platform_block, 0)}")
    parts.append("")

    # SES (from IAC config)
    ses_arn = iac_config.get("ses_identity_arn")
    if ses_arn:
        ses_arn = _resolve_templates(ses_arn, global_vars)
        parts.append("# SES Configuration for Cognito email sending")
        parts.append(f"ses_identity_arn = {_hcl(ses_arn)}")
        parts.append("")

    # Domain (from IAC config + AWS-resolved hosted_zone_id)
    domain = iac_config.get("domain")
    if domain:
        domain = dict(domain)  # shallow copy
        if hosted_zone_id:
            domain["hosted_zone_id"] = hosted_zone_id
        domain = _resolve_templates(domain, global_vars)
        parts.append("# Domain Configuration")
        parts.append(f"domain = {_hcl(domain, 0)}")
        parts.append("")

    # Services
    if ecs_services:
        parts.append(_section("Service Configuration (ECS)"))
        parts.append("")
        parts.append(_render_commented_map("services", ecs_services))
        parts.append("")

    # Bastion (from IAC config)
    bastion = iac_config.get("bastion")
    if bastion:
        parts.append("# Bastion Host Configuration")
        parts.append(f"bastion = {_hcl(bastion, 0)}")
        parts.append("")

    # Static Sites
    if static_sites:
        parts.append(_section("Static Sites Configuration (S3 + CloudFront)"))
        parts.append("")
        parts.append(_render_commented_map("static_sites", static_sites))
        parts.append("")

    # Lambda Functions (from IAC config)
    lambda_fns = iac_config.get("lambda_functions")
    if lambda_fns:
        resolved_lambdas = _resolve_templates(lambda_fns, global_vars)
        resolved_lambdas = _resolve_refs(resolved_lambdas, name_map)
        parts.append(_section("Lambda Functions Configuration"))
        parts.append("")
        parts.append(_render_commented_map("lambda_functions", resolved_lambdas))
        parts.append("")

    # EventBridge Rules (from IAC config)
    eb_rules = iac_config.get("eventbridge_rules")
    if eb_rules:
        resolved_eb = _resolve_templates(eb_rules, global_vars)
        resolved_eb = _resolve_refs(resolved_eb, name_map)
        parts.append(_section("EventBridge Rules Configuration"))
        parts.append("")
        parts.append(_render_commented_map("eventbridge_rules", resolved_eb))
        parts.append("")

    return "\n".join(parts)


# ── I/O Helpers ──────────────────────────────────────────────────────────


def write_tfvars(
    manifest: ProjectManifest,
    env_name: str,
    output_path: Path,
    *,
    resolve_aws: bool = True,
) -> Path:
    """Generate and write a ``{env}.auto.tfvars`` file.

    Args:
        manifest: A loaded ``ProjectManifest``.
        env_name: Target environment name (e.g., ``prod``).
        output_path: Absolute path to the output ``.auto.tfvars`` file.
        resolve_aws: When True, resolve values from the AWS CLI.

    Returns:
        The path to the written file.
    """
    content = generate_tfvars(manifest, env_name, resolve_aws=resolve_aws)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    return output_path


__all__ = [
    "generate_tfvars",
    "iac_service_name",
    "iac_static_site_name",
    "write_tfvars",
]
