[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foundry-cli"
version = "0.7.0"
description = "Foundry CLI - run and manage platform apps"
authors = [{name="Foundry"}]
requires-python = ">=3.9"
dependencies = [
  "click",
  "colorama",
  "jsonschema",
  "pyyaml",
  "textual==0.56.4",
  "sshtunnel>=0.4.0"
]

[project.scripts]
foundry = "foundry_cli.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]
include = ["foundry_cli*"]

[tool.setuptools.package-data]
foundry_cli = ["resources/VERSION"]