import { WikiLayout } from "@/components/WikiLayout";

export default function RuntimeConfigPage(): React.ReactElement {
  return (
    <WikiLayout title="runtime.yml" description="The team-shared runtime configuration.">
      <div className="prose-wiki max-w-3xl">
        <h1>runtime.yml</h1>

        <p>
          <code>.foundry/runtime.yml</code> is <strong>committed</strong> and shared
          with the team. It declares how to <em>run</em> each service — ports,
          start commands, environment variables, and health checks.
        </p>

        <h2>Generation</h2>
        <p>
          Generated by <code>foundry init</code> from the manifest and filesystem
          detection. Regenerate with:
        </p>
        <pre><code>foundry init --regenerate-runtime</code></pre>

        <h2>Structure</h2>
        <pre><code>{`# .foundry/runtime.yml
generatedAt: "2025-01-01T00:00:00Z"
generatedFrom: foundry.json

services:
  platform-microlith:
    kind: backend
    type: spring-boot
    port: 8081
    managementPort: 18081
    command: ./mvnw spring-boot:run
    args:
      - -Dspring-boot.run.profiles=local
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/platform
    healthCheck:
      path: /actuator/health
      port: 18081

  hub-frontend:
    kind: frontend
    type: nextjs
    port: 3000
    packageManager: pnpm
    command: pnpm dev --filter hub-frontend
    env:
      NEXT_PUBLIC_API_URL: http://localhost:8081`}</code></pre>

        <h2>Port Assignment</h2>
        <p>Ports are assigned by convention:</p>
        <table>
          <thead>
            <tr><th>Kind</th><th>Starting Port</th><th>Management Port</th></tr>
          </thead>
          <tbody>
            <tr><td>Backend</td><td>8081 (+10)</td><td>18081 (+10)</td></tr>
            <tr><td>Frontend</td><td>3000 (+1)</td><td>—</td></tr>
          </tbody>
        </table>

        <h2>Editing</h2>
        <p>
          You can edit <code>runtime.yml</code> by hand — Foundry won{"'"}t overwrite
          it unless you explicitly run <code>--regenerate-runtime</code>. Team
          members pull changes via Git.
        </p>
      </div>
    </WikiLayout>
  );
}
