from __future__ import annotations

import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from foundry_cli.core.errors import FoundryError
from foundry_cli.core.alias.store import foundry_data_dir


def _is_packaged_executable() -> bool:
    # In PyInstaller onefile/onedir builds, sys.executable points to foundry.exe.
    # In source runs it points to python.exe.
    import sys

    return sys.executable.lower().endswith("foundry.exe")


def _packaged_bin_dir() -> Path | None:
    import sys

    exe = Path(sys.executable)
    if exe.name.lower() == "foundry.exe":
        return exe.parent
    return None


def alias_bin_dir() -> Path:
    """Directory where alias shims are written.

    - Packaged install: next to `foundry.exe` (assumed on PATH via installer)
    - Source/dev: `%LOCALAPPDATA%\\Foundry\\bin` (user adds to PATH)
    """

    packaged = _packaged_bin_dir()
    if packaged is not None:
        return packaged

    # Prefer placing shims next to the `foundry` executable that the shell will
    # actually resolve on PATH. This makes `foundry alias set fr run` “just work”
    # for pip/venv installs without any `alias init` or PATH changes.
    #
    # Examples returned by `which` on Windows:
    #   C:\...\venv\Scripts\foundry.exe
    #   C:\Program Files\Foundry\foundry.exe
    which = shutil.which("foundry")
    if which:
        p = Path(which).resolve()
        if p.exists():
            return p.parent

    # Secondary heuristic: if we're running in a venv, sys.executable is usually
    # in the same Scripts directory as the console-script shims.
    import sys

    scripts_dir = Path(sys.executable).resolve().parent
    if (scripts_dir / "foundry.exe").exists() or (scripts_dir / "foundry.cmd").exists():
        return scripts_dir

    # Fallback: a dedicated bin dir under LOCALAPPDATA.
    return foundry_data_dir() / "bin"


_alias_name_re = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,30}$")


def validate_alias_name(name: str) -> None:
    if not _alias_name_re.match(name):
        raise FoundryError(
            "Invalid alias name. Use letters/numbers/dash/underscore, starting with a letter (max 31 chars)."
        )


@dataclass(frozen=True)
class ShimPaths:
    cmd: Path


def shim_paths(name: str, bin_dir: Path | None = None) -> ShimPaths:
    d = bin_dir or alias_bin_dir()
    return ShimPaths(cmd=d / f"{name}.cmd")


def write_cmd_shim(name: str, *, bin_dir: Path | None = None) -> Path:
    """Create a .cmd shim that forwards to `foundry alias exec <name>`.

    We call `foundry` by name so this works both for packaged installs and
    dev/source installs where `foundry` is available on PATH.
    """

    validate_alias_name(name)
    paths = shim_paths(name, bin_dir=bin_dir)
    paths.cmd.parent.mkdir(parents=True, exist_ok=True)

    # Packaged installs: call the adjacent `foundry.exe`.
    #
    # Source/pip installs:
    # - We *want* to call `foundry`, but pip console-scripts often invoke the
    #   Click entrypoint directly (bypassing `foundry_cli.__main__`), which means
    #   argv expansion won't run.
    # - Therefore, for the shim we call `python -m foundry_cli` (so expansion is
    #   guaranteed) and we print a one-time warning to make this visible.
    #
    # Normal alias invocation by argv0 (typing `fr ...` directly) still goes
    # through `foundry` (because the shim is `fr.cmd`), so this only affects the
    # internal dispatch hop.
    packaged = _packaged_bin_dir()
    if packaged is not None:
        runner = '"%~dp0foundry.exe"'
    else:
        import sys

        runner = f'"{sys.executable}" -m foundry_cli'

    # Important: the `alias exec` Click command is hidden and not intended for
    # direct use. We still pass through the tokens `alias exec <name>` because
    # argv expansion happens *before* Click parses commands.
    #
    # We also include `--` so any user args are treated as positional by Click
    # if argv expansion ever fails (safer around leading dashes).
    content = "\n".join(
        [
            "@echo off",
            "setlocal",
            "REM Auto-generated by Foundry CLI",
            "REM NOTE: This shim uses `python -m foundry_cli` to ensure argv expansion runs.",
            "REM If you prefer using the `foundry` entrypoint, ensure the console-script calls into foundry_cli.__main__.",
            f"{runner} alias exec {name} -- %*",
            "",
        ]
    )
    paths.cmd.write_text(content, encoding="utf-8")
    return paths.cmd


def remove_shim(name: str, *, bin_dir: Path | None = None) -> None:
    validate_alias_name(name)
    paths = shim_paths(name, bin_dir=bin_dir)
    try:
        if paths.cmd.exists():
            paths.cmd.unlink()
    except Exception as e:
        raise FoundryError(f"Failed to remove alias shim: {paths.cmd} ({e})") from e


__all__ = ["alias_bin_dir", "validate_alias_name", "write_cmd_shim", "remove_shim", "shim_paths"]
