from __future__ import annotations

import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from foundry_cli.core.errors import FoundryError
from foundry_cli.core.alias.store import foundry_data_dir


def _is_packaged_executable() -> bool:
    # In PyInstaller onefile/onedir builds, sys.executable points to foundry.exe.
    # In source runs it points to python.exe.
    import sys

    return sys.executable.lower().endswith("foundry.exe")


def _packaged_bin_dir() -> Path | None:
    import sys

    exe = Path(sys.executable)
    if exe.name.lower() == "foundry.exe":
        return exe.parent
    return None


def alias_bin_dir() -> Path:
    """Directory where alias shims are written.

    - Packaged install: next to `foundry.exe` (assumed on PATH via installer)
    - Source/dev: `%LOCALAPPDATA%\\Foundry\\bin` (user adds to PATH)
    """

    packaged = _packaged_bin_dir()
    if packaged is not None:
        return packaged

    # Prefer placing shims next to the `foundry` executable that the shell will
    # actually resolve on PATH. This makes `foundry alias set fr run` “just work”
    # for pip/venv installs without any `alias init` or PATH changes.
    #
    # Examples returned by `which` on Windows:
    #   C:\...\venv\Scripts\foundry.exe
    #   C:\Program Files\Foundry\foundry.exe
    which = shutil.which("foundry")
    if which:
        p = Path(which).resolve()
        if p.exists():
            return p.parent

    # Secondary heuristic: if we're running in a venv, sys.executable is usually
    # in the same Scripts directory as the console-script shims.
    import sys

    scripts_dir = Path(sys.executable).resolve().parent
    if (scripts_dir / "foundry.exe").exists() or (scripts_dir / "foundry.cmd").exists():
        return scripts_dir

    # Fallback: a dedicated bin dir under LOCALAPPDATA.
    return foundry_data_dir() / "bin"


_alias_name_re = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,30}$")


def validate_alias_name(name: str) -> None:
    if not _alias_name_re.match(name):
        raise FoundryError(
            "Invalid alias name. Use letters/numbers/dash/underscore, starting with a letter (max 31 chars)."
        )


@dataclass(frozen=True)
class ShimPaths:
    cmd: Path
    ps1: Path


def shim_paths(name: str, bin_dir: Path | None = None) -> ShimPaths:
    d = bin_dir or alias_bin_dir()
    return ShimPaths(cmd=d / f"{name}.cmd", ps1=d / f"{name}.ps1")


def write_cmd_shim(name: str, *, bin_dir: Path | None = None) -> Path:
    """Create .cmd and .ps1 shims implementing an alias.

    The .ps1 shim does the real work and handles Ctrl+C gracefully.
    The .cmd shim delegates to PowerShell for users in cmd.exe.
    """

    validate_alias_name(name)

    paths = shim_paths(name, bin_dir=bin_dir)
    paths.cmd.parent.mkdir(parents=True, exist_ok=True)

    from foundry_cli.core.alias.store import load_aliases

    prefix = load_aliases().aliases.get(name)
    if not prefix:
        raise FoundryError(f"Alias not found: {name}")

    packaged = _packaged_bin_dir()
    if packaged is not None:
        runner_cmd = '"%~dp0foundry.exe"'
        runner_ps1 = '"$PSScriptRoot\\foundry.exe"'
    else:
        runner_cmd = "foundry"
        runner_ps1 = "foundry"

    prefix_str = " ".join(prefix)

    # PowerShell shim - handles Ctrl+C gracefully without "Terminate batch job?" prompt
    ps1_content = "\n".join(
        [
            "# Auto-generated by Foundry CLI",
            f"& {runner_ps1} {prefix_str} @args",
            "exit $LASTEXITCODE",
            "",
        ]
    )
    paths.ps1.write_text(ps1_content, encoding="utf-8")

    # CMD shim - delegates to PowerShell to avoid "Terminate batch job?" prompt
    # The -NoProfile speeds up startup, -ExecutionPolicy Bypass ensures it runs
    cmd_content = "\n".join(
        [
            "@echo off",
            "REM Auto-generated by Foundry CLI",
            f'powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -File "%~dpn0.ps1" %*',
            "",
        ]
    )
    paths.cmd.write_text(cmd_content, encoding="utf-8")

    return paths.cmd


def remove_shim(name: str, *, bin_dir: Path | None = None) -> None:
    validate_alias_name(name)
    paths = shim_paths(name, bin_dir=bin_dir)
    try:
        if paths.cmd.exists():
            paths.cmd.unlink()
        if paths.ps1.exists():
            paths.ps1.unlink()
    except Exception as e:
        raise FoundryError(f"Failed to remove alias shim: {paths.cmd} ({e})") from e


__all__ = ["alias_bin_dir", "validate_alias_name", "write_cmd_shim", "remove_shim", "shim_paths"]
